import { Explainer } from '../components/Explainer';
import {
    ALPHA_U_COMPARISON_REFERENCE_DISPLAY,
    ALPHA_U_FORWARD_REFERENCE_DISPLAY,
    COMMON_LOAD_CAPACITY_DISPLAY,
    ELECTROWEAK_BRIDGE_CAPACITY_DISPLAY,
    FINITE_PRESENCE_CAPACITY_DISPLAY,
    PIXEL_COMPARISON_REFERENCE_DISPLAY,
    PIXEL_FORWARD_REFERENCE_DISPLAY,
    POISSON_CAPACITY_DISPLAY,
    SCREEN_CAPACITY_REFERENCE_EXACT_DISPLAY,
} from '../core/ophMath';

interface Axiom {
    id: string;
    name: string;
    plain: string;
    formal: string;
    constrains: string;
    doesNotImply: string[];
    reference: string;
}

const AXIOMS: Axiom[] = [
    {
        id: 'A1',
        name: 'Oriented Twelve-Port Observer Screen',
        plain: 'Observers live on an oriented spherical screen built from finite patches. Each local carrier exposes twelve ports on an icosahedral boundary, joins its neighbors through typed seams, keeps records and checkpoints, and carries a complete reversible infinitesimal response on those ports.',
        formal: 'For each regulator r, the observer-screen object contains a finite patch and overlap category, central records, twelve primitive port projections with oriented (12, 30, 20) boundary incidence, coherent seam cocycles, and refinement maps to an oriented spherical support. For V = R[P], there is a finite-dimensional response space H and a faithful real-linear map D: V \u2192 u(H). The image D(V) is commutator-closed and complete for the public infinitesimal port response, -Tr(D(v)D(w)) is positive definite, and the construction is natural under admissible recharting and refinement.',
        constrains: 'The local carrier geometry, observer and federation interfaces, refinement architecture, and a faithful compact commutator-closed response object complete on the declared public response tangent.',
        doesNotImply: [
            'Observer agreement or state selection',
            'Repair termination, confluence, or a global state',
            'A particular executable impulse/readback producer',
            'A compact Lie type, global gauge group, particle content, or laboratory identification by itself',
        ],
        reference: 'https://github.com/FloatingPragma/observer-patch-holography/blob/main/docs/AXIOM_REFERENCE.md#a1-oriented-twelve-port-observer-screen',
    },
    {
        id: 'A2',
        name: 'Observer Agreement',
        plain: 'Observers agree on the meaning of accepted shared data. Every proper recharting of a complete carrier is implemented by their own reversible overlap response rather than by an external relabeling.',
        formal: 'The interpretation map J_r is natural under every visible overlap, seam, recharting, federation, and refinement map. Accepted reversible overlap transports form a groupoid whose closed paths cover every orientation-preserving carrier automorphism. Each automorphism a has a projective implementer [U_a] with Ad_[U_a] D(v) = D(a.v). The implementer factors through the identity component generated by D(V), up to a unitary that centralizes D(V), and path composition is projective and refinement-natural.',
        constrains: 'Shared operational meaning, complete projective overlap holonomy, and endogenous implementation of every proper carrier symmetry by the same response object.',
        doesNotImply: [
            'Repair termination, confluence, or unique public normal forms',
            'A unique unitary lift or removal of operationally silent central factors',
            'A global compact group or laboratory-current identification',
            'The domain of accepted data, which the first axiom or an explicit interface must supply',
        ],
        reference: 'https://github.com/FloatingPragma/observer-patch-holography/blob/main/docs/AXIOM_REFERENCE.md#a2-observer-agreement',
    },
    {
        id: 'A3',
        name: 'Conditional Maximum Randomness',
        plain: 'Everything that observer agreement leaves unconstrained is maximally random. The realized state is the least informative state compatible with the shared constraints.',
        formal: '\u03c1_r = argmin over K_r of \u03a3_P w_{r,P} D(\u03c1_{r,P} \u2016 \u03c4_{r,P}). Here K_r is the nonempty convex set fixed by the finite observer-visible constraints, the first axiom supplies a state-determining cover and strictly positive exact weights, and every constraint visible to the second axiom factors through the declared constraint grammar. Identity-proportional reference densities turn this information projection into weighted local entropy maximization.',
        constrains: 'One state-selection principle: the least informative compatible family of local states relative to the exact reference and complete observer-agreement constraints.',
        doesNotImply: [
            'Independent noise or equal probabilities in every coordinate system',
            'Global thermal equilibrium or refinement compatibility without a theorem',
            'A choice among unrelated Hilbert spaces or field lists',
            'A repair law, field content, multiplicity, response law, or capacity ontology without a proved map from the selected state',
        ],
        reference: 'https://github.com/FloatingPragma/observer-patch-holography/blob/main/docs/AXIOM_REFERENCE.md#a3-conditional-maximum-randomness',
    },
];

export function AxiomsPage() {
    return (
        <div>
            <div className="section-header">
                <span className="section-tag foundation">Foundation</span>
                <h1 style={{ fontSize: '1.5rem', margin: 0 }}>The Three Axioms</h1>
            </div>

            <p style={{ marginBottom: '24px' }}>
                OPH rests on three core axioms: the oriented twelve-port observer screen, observer
                agreement, and conditional maximum randomness. Everything else is a theorem, an exact
                result inside a named finite realization, an interface requiring additional data, an independence
                result with countermodels, a physical identification, or a withdrawn claim. The paper
                surface names theorem-local premises where specific Lorentz, Einstein, or gauge
                statements are invoked; none of those premises is an axiom. The formal corpus contains
                more than 10,800 theorem and lemma declarations, and that count includes boundaries and
                countermodels as well as positive results.
            </p>

            {AXIOMS.map((ax) => (
                <div key={ax.id} className="card" style={{ marginBottom: '16px', borderLeft: '3px solid var(--accent-gold)' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '12px' }}>
                        <span style={{
                            display: 'inline-flex',
                            alignItems: 'center',
                            justifyContent: 'center',
                            width: '36px',
                            height: '36px',
                            background: 'rgba(201, 169, 110, 0.15)',
                            border: '1px solid var(--accent-gold)',
                            fontSize: '0.8em',
                            fontWeight: 700,
                            color: 'var(--accent-gold)',
                        }}>
                            {ax.id}
                        </span>
                        <h3 style={{ margin: 0, fontSize: '1em' }}>{ax.name}</h3>
                    </div>
                    <p style={{ margin: '0 0 10px', fontSize: '0.9em' }}>{ax.plain}</p>
                    <div style={{ marginBottom: '10px', fontSize: '0.82em', color: 'var(--text-secondary)' }}>
                        <strong>Concise formal statement:</strong> {ax.formal}
                    </div>
                    <div style={{ marginBottom: '8px', fontSize: '0.82em', color: 'var(--text-secondary)' }}>
                        <strong>Constrains:</strong> {ax.constrains}
                    </div>
                    <div style={{ marginBottom: '8px', fontSize: '0.82em', color: 'var(--text-secondary)' }}>
                        <strong>Does not imply:</strong>
                        <ul style={{ paddingLeft: '20px', margin: '6px 0 0', lineHeight: '1.6' }}>
                            {ax.doesNotImply.map((item) => <li key={item}>{item}</li>)}
                        </ul>
                    </div>
                    <a href={ax.reference} target="_blank" rel="noreferrer" style={{ fontSize: '0.8em' }}>
                        Canonical axiom reference
                    </a>
                </div>
            ))}

            <div className="card" style={{ marginBottom: '16px', borderLeft: '3px solid var(--accent-gold)' }}>
                <h3 style={{ margin: '0 0 10px 0', fontSize: '0.95em' }}>The Closure Principle (not an axiom)</h3>
                <p style={{ margin: '0 0 10px', fontSize: '0.9em' }}>
                    The universe is modeled as a self-referential fixed point: the simulating and the
                    simulated description are one system. Once a construction-side reading and a
                    readback-side reading have been shown to be readings of the same typed invariant,
                    self-reference forces their equality. It does not construct those readings, prove
                    their physical identity, select a branch, or guarantee existence, uniqueness, and
                    stability. Those obligations apply to every closure law. The principle
                    sits beside the axioms; every axiom count is three.
                </p>
                <ul style={{ paddingLeft: '20px', lineHeight: '1.8', margin: 0, fontSize: '0.84em' }}>
                    <li><strong>Screen-grain closure:</strong> P = &phi; + &radic;&pi;/A<sub>T</sub>(P), with one interval-certified root for each declared map. A physical fine-structure value also needs a target-independent map choice, proof that both sides read the same quantity, and same-scheme transport to the laboratory endpoint. The closest declared-map root differs from the measured value by a few parts per million.</li>
                    <li><strong>Two bridge coordinates:</strong> P<sub>C</sub> = {PIXEL_COMPARISON_REFERENCE_DISPLAY} and &alpha;<sub>U</sub>(P<sub>C</sub>) = {ALPHA_U_COMPARISON_REFERENCE_DISPLAY} give the measured-endpoint coordinate N<sub>EW</sub>(P<sub>C</sub>) = {ELECTROWEAK_BRIDGE_CAPACITY_DISPLAY}. The source-forward values P<sub>fwd</sub> = {PIXEL_FORWARD_REFERENCE_DISPLAY} and &alpha;<sub>U</sub>(P<sub>fwd</sub>) = {ALPHA_U_FORWARD_REFERENCE_DISPLAY} give N<sub>0</sub>(P<sub>fwd</sub>) = &pi;&middot;exp(6&pi;/(P<sub>fwd</sub>&middot;&alpha;<sub>U</sub>(P<sub>fwd</sub>))) = {COMMON_LOAD_CAPACITY_DISPLAY}. These branches are distinct.</li>
                    <li><strong>Finite candidate:</strong> total reserve expectation P<sub>fwd</sub>/4 and six-class equidistribution give one-class presence P<sub>fwd</sub>/24. Physical selection of one blocked class, its scalar-weighted presence receipt, and a reserve-to-global-capacity survival theorem would give N<sub>presence</sub> = N<sub>0</sub>(1 &minus; P<sub>fwd</sub>/24) = {FINITE_PRESENCE_CAPACITY_DISPLAY}.</li>
                    <li><strong>Poisson candidate:</strong> N<sub>Poisson</sub> = N<sub>0</sub>exp(&minus;P<sub>fwd</sub>/24) = {POISSON_CAPACITY_DISPLAY} needs an additional mean-count or projective-limit carrier.</li>
                    <li><strong>Physical boundary:</strong> exact neutral, one-class, and six-class compositional completions share the declared local datum and disagree globally. The declared finite-cut attachment class selects no reserve action. The Planck base-&Lambda;CDM comparison coordinate is {SCREEN_CAPACITY_REFERENCE_EXACT_DISPLAY}; the finite-presence and Poisson residuals are &minus;0.6287% and &minus;0.3880%. These target-exposed landings have no selective weight.</li>
                    <li><strong>Reopen condition:</strong> cosmic use requires a stronger target-independent source law, the inherited electroweak bridge premises, common-load identity, physical Z<sub>6</sub> seam action, and horizon-record identity.</li>
                    <li><strong>Conditional falsifier:</strong> after those physical bridges are established, a capacity confidently above N<sub>0</sub> rejects this positive-reserve candidate class. It does not by itself reject the three axioms or every possible OPH closure.</li>
                </ul>
            </div>

            <div className="card" style={{ marginBottom: '16px', borderLeft: '3px solid var(--accent-blue)' }}>
                <h3 style={{ margin: '0 0 10px 0', fontSize: '0.95em' }}>Declared Completions (not axioms)</h3>
                <div style={{ fontSize: '0.84em', color: 'var(--text-secondary)', marginBottom: '10px' }}>
                    Sector statements the finite results do not derive: each enters as an explicit declaration without a physical selection theorem
                </div>
                <ul style={{ paddingLeft: '20px', lineHeight: '1.8', margin: 0, fontSize: '0.84em' }}>
                    <li><strong>Generation count:</strong> the CP-capability and weak-sector clauses give the window 3 to 5; they do not select a count inside it, and three enters only as a declared completion.</li>
                    <li><strong>One Higgs:</strong> the finite scan fixes compatible scalar charges and channels, not scalar existence or multiplicity.</li>
                    <li><strong>No extra light sectors:</strong> no source-completeness theorem is proved; arbitrary sterile extensions are countermodels.</li>
                </ul>
                <p style={{ margin: '10px 0 0 0', fontSize: '0.82em', color: 'var(--text-muted)' }}>
                    The first two axioms force the abstract Standard Model compact Lie type. The
                    executable source current, physical matter fixture, and global quotient require
                    separate constructions.
                </p>
            </div>

            <Explainer title="Extended Inputs Beyond Core Axioms">
                <p>The papers distinguish the three axioms from theorem-local technical premises and branch conditions:</p>
                <ul style={{ paddingLeft: '20px', lineHeight: '1.8' }}>
                    <li><strong>Declared completions:</strong> the generation, scalar, and sector declarations above, none of which supplies its physical identification</li>
                    <li><strong>Transport premise:</strong> central or higher-associator strictification plus at least one allowed strict representative with trivial represented loop holonomy when global transportability is invoked</li>
                    <li><strong>Scaling premise:</strong> T2 governs the BW/null-modular and smooth physical Einstein branches. It is not needed for the exact finite source-poset theorem, the constructed ambient 1+3 Lorentz carrier, or the typed finite Einstein-shape implication. Promoting those finite results to a physical manifold and smooth Einstein dynamics requires the stated continuum certificates, including tensor-curvature convergence or the independent small-ball/null-balance identification; scalar curvature alone is diagnostic.</li>
                    <li><strong>Stationarity premise:</strong> fixed-cap generalized-entropy stationarity for the admissible first-variation class used in the Jacobson branch</li>
                    <li><strong>Collar-recovery branch:</strong> either the exact central-interface Markov route, or a faithful finite-range Gibbs family with uniform strong conditional matrix mixing and the full boundary-aware rate margin. Ordinary clustering and a bare delta/l<sub>UV</sub> &rarr; infinity ratio do not discharge this premise.</li>
                    <li><strong>Finite collar receipts:</strong> interaction bounds, boundary counts, regional CMI, matrix-defect norms, predeclared mixing constants, held-out cuts, recovery error, and rate margins are finite proxies; they do not prove a cofinal limit.</li>
                    <li><strong>Compact-gauge refinement receipt:</strong> finite-state extendability, center-compatible block-multiplicity embeddings, common stagewise strict representatives with coherent surjective boundary-group maps that intertwine them, finite tensor realizations, compatible forgetful fibers, and symmetric braiding (or an explicit super-Tannakian fork)</li>
                    <li><strong>Regulator and fixed-point premises:</strong> local factor regulation and boundary fixed-point structure used in gauge reconstruction</li>
                </ul>
            </Explainer>

            <Explainer title="What these axioms give you">
                <p>The paper surface separates structural outputs from branch-conditional ones:</p>
                <ul style={{ paddingLeft: '20px', lineHeight: '1.8' }}>
                    <li>Authenticated read-after-write provenance gives an exact finite informational causal poset, and source height is exactly its attained maximum authenticated-parent-chain length. Every finite decidable strict partial order compiles into that grammar, and every finite log has an auxiliary injective placement that sends generated ancestry into the future cone of the independently constructed rank-three 1+3 carrier. The compiler is given its order and the placement is enumeration-dependent, so neither selects physical spacetime.</li>
                    <li>For a source-selected placement, the parent-edge speed bound, equal-height spatial injectivity, and strict spacelike separation of increasing-height non-ancestors imply exact cone/order agreement; event separation and exact intervals follow. Physical coordinates, clock, signal-causal identification, manifoldlikeness, and the continuum are separate inputs.</li>
                    <li>From the screen identity and the explicit BW scaling branch, OPH recovers Lorentz kinematics on the extracted prime geometric subnet.</li>
                    <li>From the null bridge, the separate bounded-interval projective branch, and fixed-cap stationarity, OPH states a conditional Jacobson-type Einstein branch with those added ingredients kept explicit.</li>
                    <li>In a separately supplied 3+1 tensor interface on the same event type, nine source-direction balances plus Ward/Bianchi conservation and connectedness imply an exact finite Einstein-form shape. Physical fields, curvature, stress, coupling, and the smooth-limit identification are supplied.</li>
                    <li>Collar CMI controls recovery error on its exact or conditional branch. As a scalar, it is not a stress tensor or dark-sector source.</li>
                    <li>The half-line generator/null-stress charge identification is internal to the null bridge; UV/BW cap-pair extraction and ordered cut-pair rigidity are explicit scaffold items.</li>
                    <li>The complete compact response clause in the first axiom and the endogenous transport clause in the second force the abstract Lie type u(1)&oplus;su(2)&oplus;su(3) on the twelve-port branch.</li>
                    <li>Massless photon and graviton are symmetry-protected structural outputs.</li>
                </ul>
                <p>
                    Target-blind readback derives the inverse-port response, while source reconstruction
                    of the complete current is not derived. The fifteen-state fixture gives exact hypercharges,
                    anomalies, three colors, and a common Z<sub>6</sub> kernel inside its declared
                    representation class. The familiar global quotient additionally requires a complete
                    character lattice and a same-source loop-to-kernel identification. Physical matter,
                    global-form, family, and scalar selections require separate source constructions.
                </p>
            </Explainer>
        </div>
    );
}
