import { useState, useMemo } from 'react';

interface GlossaryEntry {
    term: string;
    definition: string;
    category: 'foundation' | 'chain1' | 'chain2' | 'prediction';
}

const GLOSSARY: GlossaryEntry[] = [
    {
        term: 'Holographic Screen',
        definition: 'The fundamental 2-sphere S\u00b2 on which all physical information is encoded. In OPH, spacetime is emergent; the screen is primary. The screen of a cosmological observer is their cosmic horizon.',
        category: 'foundation',
    },
    {
        term: 'Observer Patch',
        definition: 'A connected subregion P of the screen S\u00b2 accessible to a single observer. Each patch carries a von Neumann algebra A(P) of observables, a local state \u03c1_P, and a record set R_P. An observer is defined by their patch.',
        category: 'foundation',
    },
    {
        term: 'Overlap Consistency',
        definition: 'Axiom A2: where two patches P\u2081 and P\u2082 overlap, their local states must agree on the shared algebra: \u03c1\u2081|_{A(P\u2081 \u2229 P\u2082)} = \u03c1\u2082|_{A(P\u2081 \u2229 P\u2082)}. There is no God\u2019s-eye view; reality is the mutual consistency of perspectives.',
        category: 'foundation',
    },
    {
        term: 'Generalized Entropy',
        definition: 'S_gen(C) = A(\u2202C)/(4G) + S_bulk(C). The sum of the area term (Bekenstein-Hawking entropy) and the bulk von Neumann entropy. Axiom A3 requires this to satisfy quantum focusing.',
        category: 'foundation',
    },
    {
        term: 'Markov Condition',
        definition: 'Axiom A4: for tripartitions A-B-D across separators, the conditional mutual information I(A:D|B) \u2264 \u03b5. When \u03b5 \u2248 0, information is locally recoverable. When \u03b5 > 0, the Markov defect produces MOND-like effects.',
        category: 'foundation',
    },
    {
        term: 'MaxEnt',
        definition: 'Assumption B: among all states compatible with local constraints, nature selects the one maximizing von Neumann entropy. Not a dynamical law but a typicality argument \u2014 the MaxEnt state is overwhelmingly the most common.',
        category: 'foundation',
    },
    {
        term: 'Von Neumann Algebra',
        definition: 'A *-algebra of bounded operators on a Hilbert space that is closed in the weak operator topology. In OPH, each patch carries a von Neumann algebra. Type III\u2081 factors arise naturally for quantum field theoretic patches.',
        category: 'foundation',
    },
    {
        term: 'Bekenstein-Hawking Entropy',
        definition: 'S_BH = A/(4l_P\u00b2). The entropy of a black hole equals its horizon area in Planck units divided by 4. Generalized to any surface in OPH via Axiom A3.',
        category: 'chain1',
    },
    {
        term: 'Ryu-Takayanagi Formula',
        definition: 'S(A) = Area(\u03b3_A)/(4G_N). The entanglement entropy of a boundary region A equals the area of the minimal bulk surface \u03b3_A homologous to A. The bridge between entanglement and geometry.',
        category: 'chain1',
    },
    {
        term: 'Conformal Group',
        definition: 'Conf\u207a(S\u00b2) = PSL(2,\u2102) \u2245 SO\u207a(3,1). The orientation-preserving conformal transformations of S\u00b2, isomorphic to the proper orthochronous Lorentz group. This identity derives 3+1D spacetime from the 2D screen.',
        category: 'chain1',
    },
    {
        term: 'M\u00f6bius Transformation',
        definition: 'z \u21a6 (az+b)/(cz+d) with ad-bc=1. Conformal maps of the Riemann sphere \u2102\u222a{\u221e}. They are the screen manifestation of Lorentz boosts, rotations, and null rotations.',
        category: 'chain1',
    },
    {
        term: 'Modular Flow',
        definition: '\u03c3_t(A) = \u0394^{it}A\u0394^{-it}. The one-parameter automorphism group generated by the modular operator \u0394 of Tomita-Takesaki theory. For Rindler wedges, modular flow equals Lorentz boost (BW theorem).',
        category: 'chain1',
    },
    {
        term: 'Bisognano-Wichmann Theorem',
        definition: 'K_C = 2\u03c0 \u00b7 B_C. The modular Hamiltonian of the vacuum for a Rindler wedge equals 2\u03c0 times the boost generator. Connects modular theory to spacetime geometry.',
        category: 'chain1',
    },
    {
        term: 'Unruh Temperature',
        definition: 'T_U = \u0127a/(2\u03c0ck_B). An accelerating observer with proper acceleration a sees the vacuum as a thermal state at temperature T_U. A consequence of the BW theorem.',
        category: 'chain1',
    },
    {
        term: 'Entanglement Equilibrium',
        definition: '\u03b4S_gen = 0. The condition that generalized entropy is stationary under first-order perturbations. Combined with the Clausius relation \u03b4Q = TdS, this implies Einstein\u2019s equations.',
        category: 'chain1',
    },
    {
        term: 'MOND Scale a\u2080',
        definition: 'a\u2080 = (15/8\u03c0\u00b2)c\u00b2\u221a(\u039b/3) \u2248 1.03\u00d710\u207b\u00b9\u2070 m/s\u00b2. The acceleration scale below which Newtonian gravity fails. Derived in OPH from the Markov defect, not postulated.',
        category: 'chain1',
    },
    {
        term: 'Born Rule',
        definition: 'p = Tr(\u03c1P). The probability of outcome P is the trace of the density matrix times the projection. In OPH, derived from overlap consistency via Gleason\u2019s theorem.',
        category: 'chain2',
    },
    {
        term: 'Tsirelson Bound',
        definition: 'S \u2264 2\u221a2. The maximum CHSH correlator achievable by quantum mechanics. Exceeds the classical bound of 2 but falls short of the algebraic maximum of 4.',
        category: 'chain2',
    },
    {
        term: 'Gauge-as-Gluing',
        definition: 'Assumption D: gauge symmetry arises from the redundancy of describing the same observables on overlapping patches. Transition functions form the gauge group. Not postulated but derived from patch structure.',
        category: 'chain2',
    },
    {
        term: 'Tannaka-Krein Reconstruction',
        definition: 'A theorem that reconstructs a compact group G from its representation category Rep(G). In OPH, applied to edge-sector fusion rules to derive the gauge group.',
        category: 'chain2',
    },
    {
        term: 'Edge Modes',
        definition: 'Degrees of freedom living on the boundary \u2202P of a patch. They transform under representations of the gauge group and contribute to the entanglement entropy. Their fusion rules determine the gauge group via Tannaka-Krein.',
        category: 'chain2',
    },
    {
        term: 'Heat-Kernel Law',
        definition: 'p_R = d_R \u00b7 exp(-t\u00b7C\u2082(R))/Z. The probability for an edge sector to carry representation R, weighted by dimension d_R and Casimir C\u2082(R). The unique MaxEnt distribution over representations.',
        category: 'chain2',
    },
    {
        term: 'Z\u2086 Defect',
        definition: 'A central defect on triple patch overlaps valued in the center Z\u2086 of the SM gauge group. Responsible for the Yukawa hierarchy y_f ~ 6^{-n_f} and the CKM matrix structure.',
        category: 'chain2',
    },
    {
        term: 'Peter-Weyl Mechanism',
        definition: 'The second-index contribution of edge modes in the Peter-Weyl decomposition L\u00b2(G) = \u2295_R V_R \u2297 V_R*. Produces MSSM-like beta-function shifts without superpartners.',
        category: 'chain2',
    },
    {
        term: 'HaPPY Code',
        definition: 'A holographic quantum error-correcting code (Pastawski-Yoshida-Harlow-Preskill) using perfect tensors on a hyperbolic tiling. Demonstrates subregion duality and the RT formula in a toy model.',
        category: 'chain2',
    },
    {
        term: 'GW Frequency Comb',
        definition: 'x_k = ln(k)/(8\u03c0). The predicted discrete frequency spectrum of gravitational waves from black hole ringdown. A smoking-gun signature of the quantized area spectrum in OPH.',
        category: 'prediction',
    },
    {
        term: 'Pixel Area',
        definition: 'a_cell \u2248 1.63 l_P\u00b2. The area of a single fundamental pixel on the holographic screen. One of the two free parameters of OPH. Sets the discreteness scale of spacetime.',
        category: 'prediction',
    },
    {
        term: 'Screen Capacity',
        definition: 'log(dim H_tot) \u2248 10\u00b9\u00b2\u00b2. The total information capacity of the holographic screen in nats. One of the two free parameters of OPH. Sets the cosmological constant and MOND scale.',
        category: 'prediction',
    },
    {
        term: 'Entanglement Wedge',
        definition: 'The bulk region that can be reconstructed from a boundary subregion A. Bounded by the RT surface \u03b3_A. The domain of subregion duality and entanglement wedge reconstruction.',
        category: 'chain1',
    },
    {
        term: 'KMS Condition',
        definition: '\u03c9(A\u00b7\u03b1_t(B)) = \u03c9(\u03b1_{t+i\u03b2}(B)\u00b7A). The Kubo-Martin-Schwinger condition for thermal equilibrium at inverse temperature \u03b2. In OPH, every faithful state satisfies KMS with respect to its own modular flow.',
        category: 'chain1',
    },
];

const CATEGORY_LABELS: Record<string, { label: string; color: string }> = {
    foundation: { label: 'Foundation', color: 'var(--accent-gold)' },
    chain1: { label: 'Chain 1: GR', color: 'var(--accent-rose)' },
    chain2: { label: 'Chain 2: QFT', color: 'var(--accent-blue)' },
    prediction: { label: 'Predictions', color: 'var(--accent-green)' },
};

export function GlossaryPage() {
    const [search, setSearch] = useState('');
    const [filterCategory, setFilterCategory] = useState<string | null>(null);

    const filtered = useMemo(() => {
        return GLOSSARY
            .filter(entry => {
                const matchesSearch = search === '' ||
                    entry.term.toLowerCase().includes(search.toLowerCase()) ||
                    entry.definition.toLowerCase().includes(search.toLowerCase());
                const matchesCategory = !filterCategory || entry.category === filterCategory;
                return matchesSearch && matchesCategory;
            })
            .sort((a, b) => a.term.localeCompare(b.term));
    }, [search, filterCategory]);

    return (
        <div>
            <div className="section-header">
                <span className="section-tag foundation">Reference</span>
                <h1 style={{ fontSize: '1.5rem', margin: 0 }}>Glossary</h1>
            </div>

            <p style={{ marginBottom: '16px' }}>
                Key terms and concepts in Observer Patch Holography. Use the search box to filter or click a
                category to narrow down the list.
            </p>

            <div style={{ display: 'flex', gap: '12px', marginBottom: '16px', flexWrap: 'wrap' }}>
                <input
                    type="text"
                    placeholder="Search terms..."
                    value={search}
                    onChange={e => setSearch(e.target.value)}
                    style={{
                        flex: 1,
                        minWidth: '200px',
                        padding: '8px 12px',
                        background: 'var(--bg-tertiary)',
                        border: '1px solid var(--border-color)',
                        color: 'var(--text-primary)',
                        fontFamily: 'var(--font-mono)',
                        fontSize: '0.85em',
                    }}
                />
            </div>

            <div style={{ display: 'flex', gap: '8px', marginBottom: '24px', flexWrap: 'wrap' }}>
                <button
                    className={`btn ${filterCategory === null ? 'btn-primary' : 'btn-ghost'}`}
                    onClick={() => setFilterCategory(null)}
                    style={{ fontSize: '0.75em', padding: '4px 10px' }}
                >
                    All ({GLOSSARY.length})
                </button>
                {Object.entries(CATEGORY_LABELS).map(([key, { label }]) => (
                    <button
                        key={key}
                        className={`btn ${filterCategory === key ? 'btn-primary' : 'btn-ghost'}`}
                        onClick={() => setFilterCategory(filterCategory === key ? null : key)}
                        style={{ fontSize: '0.75em', padding: '4px 10px' }}
                    >
                        {label} ({GLOSSARY.filter(e => e.category === key).length})
                    </button>
                ))}
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                {filtered.map((entry, i) => {
                    const cat = CATEGORY_LABELS[entry.category];
                    return (
                        <div key={i} className="card" style={{ borderLeft: `3px solid ${cat.color}`, padding: '16px' }}>
                            <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '8px' }}>
                                <h4 style={{ margin: 0, fontSize: '0.9em', flex: 1 }}>{entry.term}</h4>
                                <span style={{
                                    fontSize: '0.65em',
                                    padding: '2px 8px',
                                    border: `1px solid ${cat.color}`,
                                    color: cat.color,
                                    textTransform: 'uppercase',
                                    letterSpacing: '0.1em',
                                    whiteSpace: 'nowrap',
                                }}>
                                    {cat.label}
                                </span>
                            </div>
                            <p style={{ margin: 0, fontSize: '0.85em', lineHeight: '1.6' }}>{entry.definition}</p>
                        </div>
                    );
                })}
            </div>

            {filtered.length === 0 && (
                <div style={{ padding: '32px', textAlign: 'center', color: 'var(--text-muted)' }}>
                    No matching terms found. Try a different search.
                </div>
            )}
        </div>
    );
}
