import { Explainer } from '../components/Explainer';

export function LorentzPage() {
    return (
        <div>
            <div className="section-header">
                <span className="section-tag gr">Chain 1: GR</span>
                <h1 style={{ fontSize: '1.5rem', margin: 0 }}>Lorentz from the Screen</h1>
            </div>

            <p style={{ marginBottom: '16px' }}>
                On the current OPH paper surface, Lorentz kinematics is recovered on an explicit geometric modular
                branch rather than as a generic fixed-cutoff identity. The mathematical backbone is the conformal
                symmetry group of the holographic screen S&sup2;.
            </p>
            <p style={{ marginBottom: '24px' }}>
                The key identity is a classical result in mathematics:
            </p>

            <div className="math-block" style={{ fontSize: '1.1em' }}>
                Conf&#8314;(S&sup2;) = PSL(2,ℂ) ≅ SO&#8314;(3,1)
            </div>

            <p style={{ marginBottom: '16px' }}>
                The group of orientation-preserving conformal transformations of the 2-sphere is isomorphic to the
                proper orthochronous Lorentz group in 3+1 dimensions. In OPH, this is the ambient kinematic group
                available on the screen and the group recovered on the explicit BW branch.
            </p>

            <h3 style={{ fontSize: '1em', marginTop: '32px' }}>M&ouml;bius Transformations</h3>
            <p style={{ marginBottom: '8px' }}>
                A conformal map of S&sup2; (viewed as the Riemann sphere ℂ &cup; {'{'}&infin;{'}'})
                is a M&ouml;bius transformation:
            </p>
            <div className="math-block">
                z ↦ (az + b) / (cz + d), &nbsp;&nbsp; ad &minus; bc = 1
            </div>
            <p style={{ marginBottom: '16px' }}>
                where a, b, c, d &isin; ℂ. The matrix (<sup>a b</sup>/<sub>c d</sub>&rpar;
                is an element of SL(2,ℂ), and since &plusmn;I give the same transformation, the effective
                group is PSL(2,ℂ) = SL(2,ℂ)/{'{'}&plusmn;I{'}'}.
            </p>

            <h3 style={{ fontSize: '1em', marginTop: '32px' }}>The Celestial Sphere</h3>
            <p style={{ marginBottom: '16px' }}>
                Here is the physical picture. An observer at a point in Minkowski spacetime sees light arriving
                from all directions. These directions form a sphere &mdash; the <strong>celestial sphere</strong>.
                When the observer boosts (changes velocity), the pattern of light on this sphere transforms by
                a M&ouml;bius map. This is exactly the aberration of starlight.
            </p>
            <p style={{ marginBottom: '16px' }}>
                Penrose recognized that the celestial sphere IS the Riemann sphere, and Lorentz boosts ARE conformal
                maps. A boost in the z-direction dilates one hemisphere and compresses the other. A rotation is
                a rigid rotation of the sphere. Together they generate the full Lorentz group.
            </p>

            <div className="card" style={{ marginBottom: '24px', borderLeft: '3px solid var(--accent-rose)' }}>
                <h4 style={{ margin: '0 0 12px 0', fontSize: '0.9em' }}>Key Lorentz Subgroups as Screen Actions</h4>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px', fontSize: '0.85em' }}>
                    <div style={{ padding: '12px', background: 'rgba(0,0,0,0.2)', border: '1px solid var(--border-color)' }}>
                        <div style={{ color: 'var(--accent-rose)', fontWeight: 600, marginBottom: '4px' }}>Rotations SO(3)</div>
                        <div style={{ color: 'var(--text-secondary)' }}>
                            Rigid rotations of S&sup2;. Correspond to SU(2)/ℤ<sub>2</sub> &sub; PSL(2,ℂ).
                            The celestial sphere rotates.
                        </div>
                    </div>
                    <div style={{ padding: '12px', background: 'rgba(0,0,0,0.2)', border: '1px solid var(--border-color)' }}>
                        <div style={{ color: 'var(--accent-blue)', fontWeight: 600, marginBottom: '4px' }}>Boosts</div>
                        <div style={{ color: 'var(--text-secondary)' }}>
                            Dilations of the sphere about an axis. Stars bunch up in the forward direction (headlight effect).
                            Generated by z ↦ e<sup>&lambda;</sup>z.
                        </div>
                    </div>
                    <div style={{ padding: '12px', background: 'rgba(0,0,0,0.2)', border: '1px solid var(--border-color)' }}>
                        <div style={{ color: 'var(--accent-gold)', fontWeight: 600, marginBottom: '4px' }}>Null Rotations</div>
                        <div style={{ color: 'var(--text-secondary)' }}>
                            Translations on the sphere: z ↦ z + b. These correspond to Lorentz transformations
                            that leave a null direction fixed.
                        </div>
                    </div>
                    <div style={{ padding: '12px', background: 'rgba(0,0,0,0.2)', border: '1px solid var(--border-color)' }}>
                        <div style={{ color: 'var(--accent-green)', fontWeight: 600, marginBottom: '4px' }}>Special Conformal</div>
                        <div style={{ color: 'var(--text-secondary)' }}>
                            Inversions: z ↦ 1/(cz + d). Combine with translations to generate the full group.
                        </div>
                    </div>
                </div>
            </div>

            <h3 style={{ fontSize: '1em', marginTop: '32px' }}>3+1 Dimensions from 2D</h3>
            <p style={{ marginBottom: '16px' }}>
                This is not just a mathematical curiosity. In OPH, the screen S&sup2; is the fundamental arena
                (Axiom A1). The conformal group of that 2-sphere is the connected Lorentz group of 3+1 dimensions,
                which is why the Lorentz branch is screen-based rather than postulated from bulk spacetime.
                The correspondence is:
            </p>

            <div className="card" style={{ marginBottom: '24px' }}>
                <div style={{ display: 'grid', gridTemplateColumns: 'auto 1fr', gap: '8px 16px', fontSize: '0.85em' }}>
                    <span style={{ color: 'var(--accent-cyan)' }}>Screen dimension:</span>
                    <span style={{ color: 'var(--text-secondary)' }}>2 (the sphere S&sup2;)</span>
                    <span style={{ color: 'var(--accent-cyan)' }}>Conformal group:</span>
                    <span style={{ color: 'var(--text-secondary)' }}>PSL(2,ℂ) ≅ SO&#8314;(3,1)</span>
                    <span style={{ color: 'var(--accent-cyan)' }}>Spacetime dimension:</span>
                    <span style={{ color: 'var(--text-secondary)' }}>3+1 (Lorentz signature)</span>
                    <span style={{ color: 'var(--accent-cyan)' }}>Why 3+1?</span>
                    <span style={{ color: 'var(--text-secondary)' }}>Because the screen is S&sup2;, and Conf&#8314;(S&sup2;) = SO&#8314;(3,1)</span>
                </div>
            </div>

            <p style={{ marginBottom: '16px' }}>
                If the screen were S&sup1; (a circle), the conformal group would be SL(2,ℝ) ≅ SO&#8314;(2,1),
                giving 2+1D spacetime. If it were S&sup3;, the conformal group would be SO&#8314;(4,1), giving 4+1D.
                In the OPH setup the screen is S&sup2;, so the recovered Lorentz/conformal kinematics is 3+1D.
            </p>

            <div className="card" style={{ marginBottom: '24px', borderLeft: '3px solid var(--accent-gold)' }}>
                <h4 style={{ margin: '0 0 12px 0', fontSize: '0.9em', color: 'var(--accent-gold)' }}>
                    Current claim boundary
                </h4>
                <p style={{ margin: '0 0 8px 0', fontSize: '0.85em' }}>
                    The screen identity Conf<sup>+</sup>(S&sup2;) ≅ SO<sup>+</sup>(3,1) is exact mathematics. The OPH claim that
                    local modular flow realizes this geometry is stated on the explicit BW branch of the scaling-limit
                    cap theory.
                </p>
                <p style={{ margin: 0, fontSize: '0.85em', color: 'var(--text-secondary)' }}>
                    The remaining UV/BW scaffold is the realized scaling-limit cap-pair extraction plus ordered cut-pair
                    rigidity on that realized limit.
                </p>
            </div>

            <Explainer title="Spinors from the screen">
                <p>
                    The double cover of SO&#8314;(3,1) is SL(2,ℂ), which acts naturally on 2-component spinors.
                    Since the screen is S&sup2; = ℂP&sup1;, the fundamental screen degrees of freedom are
                    spinorial: they are 2-component complex objects (z<sub>0</sub>, z<sub>1</sub>) with z = z<sub>1</sub>/z<sub>0</sub>.
                </p>
                <p>
                    Spinors are therefore not exotic mathematical objects imposed on spacetime. They are the natural
                    coordinates of the screen. The fact that fermions are spin-1/2 objects is a direct consequence of
                    the screen being S&sup2;.
                </p>
            </Explainer>

            <Explainer title="BMS group and asymptotic symmetries">
                <p>
                    At null infinity of an asymptotically flat spacetime, the symmetry group is not just the Lorentz
                    group but the infinite-dimensional <strong>BMS group</strong>: the semi-direct product of the
                    Lorentz group with an infinite-dimensional group of supertranslations.
                </p>
                <p>
                    In OPH terms, the BMS group arises from diffeomorphisms of the screen that go beyond conformal
                    maps. These supertranslations are related to soft graviton theorems and gravitational memory
                    effects &mdash; all of which have a natural screen interpretation.
                </p>
            </Explainer>

            <Explainer title="Why not higher dimensions?">
                <p>
                    String theory predicts 10 or 11 spacetime dimensions and must compactify the extras. In OPH, there
                    is no compactification problem because there are no extra dimensions to begin with. The screen is
                    S&sup2;, the conformal group is SO&#8314;(3,1), and spacetime is 3+1D. The question "why 3+1?" is
                    answered: because the screen is a 2-sphere, and that is the simplest surface with complex structure.
                </p>
            </Explainer>
        </div>
    );
}
