import { Explainer } from '../components/Explainer';

const FERMION_MASSES = [
    { name: 'top (t)', mass: 172760, nf: 0, predicted: 172500, unit: 'MeV' },
    { name: 'bottom (b)', mass: 4180, nf: 1, predicted: 4200, unit: 'MeV' },
    { name: 'charm (c)', mass: 1270, nf: 2, predicted: 1300, unit: 'MeV' },
    { name: 'strange (s)', mass: 93, nf: 3, predicted: 95, unit: 'MeV' },
    { name: 'muon (mu)', mass: 105.66, nf: 3, predicted: 108, unit: 'MeV' },
    { name: 'down (d)', mass: 4.7, nf: 4, predicted: 4.8, unit: 'MeV' },
    { name: 'up (u)', mass: 2.2, nf: 5, predicted: 2.3, unit: 'MeV' },
    { name: 'electron (e)', mass: 0.511, nf: 5, predicted: 0.52, unit: 'MeV' },
    { name: 'tau (tau)', mass: 1776.9, nf: 2, predicted: 1780, unit: 'MeV' },
];

export function MassesPage() {
    const maxLogMass = Math.log10(172760);
    const minLogMass = Math.log10(0.511);
    const logRange = maxLogMass - minLogMass;

    return (
        <div>
            <div className="section-header">
                <span className="section-tag qft">Chain 2: QFT</span>
                <h1 style={{ fontSize: '1.5rem', margin: 0 }}>Particle Masses &amp; Yukawa Hierarchy</h1>
            </div>

            <p style={{ marginBottom: '16px' }}>
                One of the deepest mysteries of the Standard Model: why do fermion masses span five orders of
                magnitude? The top quark is 340,000 times heavier than the electron. In the Standard Model,
                each mass is set by an independent Yukawa coupling &mdash; a free parameter with no explanation.
            </p>
            <p style={{ marginBottom: '24px' }}>
                In OPH, the Yukawa hierarchy is <strong>generated by a Z<sub>6</sub> defect</strong> on triple
                patch overlaps. The fermion Yukawa couplings follow a geometric pattern:
            </p>

            <div className="math-block" style={{ fontSize: '1.1em' }}>
                y<sub>f</sub> &sim; 6<sup>&minus;n<sub>f</sub></sup>
            </div>

            <p style={{ marginBottom: '16px' }}>
                where n<sub>f</sub> is an integer "winding number" associated with each fermion. The heaviest
                fermion (top quark) has n<sub>f</sub> = 0 (y<sub>t</sub> &asymp; 1), and lighter fermions have
                increasing n<sub>f</sub>.
            </p>

            <h3 style={{ fontSize: '1em', marginTop: '32px' }}>The Z<sub>6</sub> Defect</h3>
            <p style={{ marginBottom: '16px' }}>
                Assumption E introduces a <strong>central defect</strong> on triple overlaps of patches. When
                three patches P<sub>1</sub>, P<sub>2</sub>, P<sub>3</sub> have a common triple overlap, the
                transition functions on the three pairwise overlaps must satisfy a cocycle condition up to a
                central element.
            </p>
            <p style={{ marginBottom: '16px' }}>
                The center of SU(3) &times; SU(2) &times; U(1) / (discrete quotient) is Z<sub>6</sub>. The
                defect valued in Z<sub>6</sub> creates a discrete "winding" that suppresses Yukawa couplings
                exponentially. The base of the exponential (6) comes from the order of Z<sub>6</sub> = Z<sub>6</sub>.
            </p>

            <h3 style={{ fontSize: '1em', marginTop: '32px' }}>Mass Spectrum Visualization</h3>
            <div className="demo-container">
                <div className="demo-label">Fermion Mass Spectrum (log scale)</div>
                <p style={{ fontSize: '0.85em', color: 'var(--text-muted)', marginBottom: '16px' }}>
                    Each bar represents a fermion mass on a logarithmic scale. The geometric spacing (factor of ~6
                    between successive levels) is the signature of the Z<sub>6</sub> defect.
                </p>

                <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
                    {FERMION_MASSES.sort((a, b) => b.mass - a.mass).map((f, i) => {
                        const logMass = Math.log10(f.mass);
                        const frac = (logMass - minLogMass) / logRange;
                        const colors = [
                            'var(--accent-rose)', 'var(--accent-blue)', 'var(--accent-cyan)',
                            'var(--accent-gold)', 'var(--accent-purple)', 'var(--accent-green)',
                            'var(--accent-amber)', 'var(--accent-rose)', 'var(--accent-blue)',
                        ];
                        return (
                            <div key={i} style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                                <span style={{ fontSize: '0.75em', color: colors[i], minWidth: '70px', textAlign: 'right', fontWeight: 600 }}>
                                    {f.name}
                                </span>
                                <div style={{ flex: 1, height: '16px', background: 'rgba(0,0,0,0.3)', border: '1px solid var(--border-color)', position: 'relative' }}>
                                    <div style={{
                                        width: `${frac * 100}%`,
                                        height: '100%',
                                        background: colors[i],
                                        opacity: 0.6,
                                    }} />
                                </div>
                                <span style={{ fontSize: '0.7em', color: 'var(--text-muted)', minWidth: '80px' }}>
                                    {f.mass >= 1000 ? `${(f.mass / 1000).toFixed(1)} GeV` : `${f.mass.toFixed(2)} MeV`}
                                </span>
                                <span style={{ fontSize: '0.7em', color: 'var(--accent-gold)', minWidth: '40px' }}>
                                    n={f.nf}
                                </span>
                            </div>
                        );
                    })}
                </div>

                <div style={{ marginTop: '16px', padding: '12px', background: 'rgba(0,0,0,0.2)', border: '1px solid var(--border-color)', fontSize: '0.8em' }}>
                    <div style={{ color: 'var(--accent-gold)', fontWeight: 600, marginBottom: '4px' }}>
                        Pattern: y<sub>f</sub> &sim; 6<sup>&minus;n</sup>
                    </div>
                    <div style={{ color: 'var(--text-secondary)' }}>
                        6<sup>0</sup> = 1, &nbsp;
                        6<sup>&minus;1</sup> &asymp; 0.17, &nbsp;
                        6<sup>&minus;2</sup> &asymp; 0.028, &nbsp;
                        6<sup>&minus;3</sup> &asymp; 0.0046, &nbsp;
                        6<sup>&minus;4</sup> &asymp; 0.00077, &nbsp;
                        6<sup>&minus;5</sup> &asymp; 0.00013
                    </div>
                </div>
            </div>

            <h3 style={{ fontSize: '1em', marginTop: '32px' }}>The Higgs Mass from Criticality</h3>
            <p style={{ marginBottom: '8px' }}>
                The Higgs boson mass is not a random parameter in OPH. It is fixed by the condition that the
                electroweak vacuum is at the boundary between stability and metastability &mdash; the
                <strong> criticality condition</strong>:
            </p>
            <div className="math-block" style={{ fontSize: '1.1em' }}>
                m<sub>H</sub> &asymp; 125.08 GeV
            </div>
            <p style={{ marginBottom: '16px' }}>
                The measured Higgs mass is 125.09 &plusmn; 0.24 GeV. The criticality prediction matches to
                within experimental uncertainty. This is remarkable: the Higgs mass is not a free parameter
                but a <em>derived quantity</em>.
            </p>
            <p style={{ marginBottom: '16px' }}>
                The criticality condition arises because the screen-sector dynamics (MaxEnt on the Higgs
                field configuration space) drives the Higgs self-coupling to the boundary of the stability
                region. At this critical point, the effective potential &lambda;(&mu;) crosses zero at high
                energy scales, which pins m<sub>H</sub> &asymp; 125 GeV given m<sub>t</sub> &asymp; 173 GeV.
            </p>

            <h3 style={{ fontSize: '1em', marginTop: '32px' }}>The CKM Matrix</h3>
            <p style={{ marginBottom: '16px' }}>
                The Cabibbo-Kobayashi-Maskawa (CKM) matrix describes quark flavor mixing. Its elements
                V<sub>ij</sub> determine the probability of transitions between quark generations. In OPH,
                the CKM matrix structure follows from the Z<sub>6</sub> defect:
            </p>
            <div className="card" style={{ marginBottom: '24px' }}>
                <div style={{ display: 'grid', gridTemplateColumns: 'auto auto auto auto', gap: '8px', fontSize: '0.85em', textAlign: 'center' }}>
                    <div></div>
                    <div style={{ color: 'var(--accent-cyan)', fontWeight: 600 }}>d</div>
                    <div style={{ color: 'var(--accent-cyan)', fontWeight: 600 }}>s</div>
                    <div style={{ color: 'var(--accent-cyan)', fontWeight: 600 }}>b</div>

                    <div style={{ color: 'var(--accent-rose)', fontWeight: 600 }}>u</div>
                    <div style={{ padding: '4px', background: 'rgba(0,255,65,0.1)' }}>0.974</div>
                    <div style={{ padding: '4px', background: 'rgba(255,179,0,0.1)' }}>0.225</div>
                    <div style={{ padding: '4px', background: 'rgba(201,112,112,0.1)' }}>0.004</div>

                    <div style={{ color: 'var(--accent-rose)', fontWeight: 600 }}>c</div>
                    <div style={{ padding: '4px', background: 'rgba(255,179,0,0.1)' }}>0.225</div>
                    <div style={{ padding: '4px', background: 'rgba(0,255,65,0.1)' }}>0.973</div>
                    <div style={{ padding: '4px', background: 'rgba(255,179,0,0.1)' }}>0.041</div>

                    <div style={{ color: 'var(--accent-rose)', fontWeight: 600 }}>t</div>
                    <div style={{ padding: '4px', background: 'rgba(201,112,112,0.1)' }}>0.009</div>
                    <div style={{ padding: '4px', background: 'rgba(255,179,0,0.1)' }}>0.040</div>
                    <div style={{ padding: '4px', background: 'rgba(0,255,65,0.1)' }}>0.999</div>
                </div>
                <p style={{ margin: '12px 0 0', fontSize: '0.8em', color: 'var(--text-muted)' }}>
                    |V<sub>CKM</sub>| values. The hierarchical structure (diagonal dominance, Cabibbo suppression)
                    follows from the Z<sub>6</sub> winding number differences between generations.
                </p>
            </div>

            <Explainer title="Why factor of 6?">
                <p>
                    The specific base of the geometric hierarchy (6) is not arbitrary. It equals the order of the
                    center Z<sub>6</sub> of the Standard Model gauge group (more precisely, the fundamental group
                    of [SU(3) &times; SU(2) &times; U(1)] / Z<sub>6</sub>).
                </p>
                <p>
                    The Z<sub>6</sub> structure arises because the Standard Model gauge group has a Z<sub>6</sub>
                    quotient: the combination (e<sup>2&pi;i/3</sup>, &minus;1, e<sup>i&pi;/3</sup>) acts trivially
                    on all Standard Model fields. This discrete symmetry is the seed of the mass hierarchy.
                </p>
            </Explainer>

            <Explainer title="Neutrino masses">
                <p>
                    Neutrinos have tiny masses (&lt; 0.1 eV) that are at least 6 orders of magnitude smaller than
                    the electron mass. In OPH, neutrino masses arise from a <strong>different mechanism</strong>
                    than charged fermion masses: they are generated by the seesaw mechanism with a right-handed
                    neutrino mass scale set by the screen capacity.
                </p>
                <p>
                    The extreme lightness of neutrinos is related to the Z<sub>6</sub> defect acting on the
                    lepton sector with maximum winding, combined with the seesaw suppression factor M<sub>R</sub>.
                </p>
            </Explainer>

            <Explainer title="Vacuum stability and the Higgs">
                <p>
                    The measured Higgs mass (125.09 GeV) and top quark mass (172.76 GeV) place the Standard Model
                    vacuum in a peculiar state: it is <strong>metastable</strong>. The Higgs self-coupling
                    &lambda;(&mu;) runs to negative values at &mu; &sim; 10<sup>10</sup> GeV, but the tunneling
                    rate is cosmologically long (&tau; &gt;&gt; age of universe).
                </p>
                <p>
                    In OPH, this near-criticality is not a coincidence but a <em>prediction</em>. The MaxEnt
                    selection on the Higgs field space drives the system to the critical boundary. The Higgs mass
                    is determined by the requirement &lambda;(&mu;<sub>instability</sub>) &asymp; 0 combined with
                    the measured m<sub>t</sub>.
                </p>
            </Explainer>
        </div>
    );
}
