import { Explainer } from '../components/Explainer';

export function ModularFlowPage() {
    return (
        <div>
            <div className="section-header">
                <span className="section-tag gr">Chain 1: GR</span>
                <h1 style={{ fontSize: '1.5rem', margin: 0 }}>Modular Flow</h1>
            </div>

            <p style={{ marginBottom: '16px' }}>
                Modular flow is the mathematical engine that connects quantum information to spacetime geometry.
                In the OPH derivation of Einstein's equations, it plays the role of <strong>local time evolution</strong>:
                the "time" experienced by an observer near their horizon is not fundamental but emerges from the
                modular automorphism of their local algebra.
            </p>

            <h3 style={{ fontSize: '1em', marginTop: '32px' }}>Tomita-Takesaki Modular Theory</h3>
            <p style={{ marginBottom: '16px' }}>
                Given a von Neumann algebra A (the observables of a patch) and a cyclic separating state |&Omega;⟩
                (the vacuum), the Tomita-Takesaki theorem constructs two operators:
            </p>

            <div className="card" style={{ marginBottom: '16px', borderLeft: '3px solid var(--accent-rose)' }}>
                <div style={{ display: 'grid', gridTemplateColumns: 'auto 1fr', gap: '8px 16px', fontSize: '0.85em' }}>
                    <span style={{ color: 'var(--accent-cyan)', fontWeight: 600 }}>S</span>
                    <span style={{ color: 'var(--text-secondary)' }}>
                        The Tomita operator: S(A|&Omega;⟩) = A†|&Omega;⟩ for A &isin; A
                    </span>
                    <span style={{ color: 'var(--accent-cyan)', fontWeight: 600 }}>&Delta; = S†S</span>
                    <span style={{ color: 'var(--text-secondary)' }}>
                        The modular operator: a positive self-adjoint operator
                    </span>
                    <span style={{ color: 'var(--accent-cyan)', fontWeight: 600 }}>J</span>
                    <span style={{ color: 'var(--text-secondary)' }}>
                        The modular conjugation: S = J&Delta;<sup>1/2</sup> (polar decomposition)
                    </span>
                </div>
            </div>

            <p style={{ marginBottom: '8px' }}>
                The <strong>modular automorphism group</strong> is a one-parameter family of automorphisms:
            </p>
            <div className="math-block">
                &sigma;<sub>t</sub>(A) = &Delta;<sup>it</sup> A &Delta;<sup>&minus;it</sup>, &nbsp;&nbsp; A &isin; A
            </div>
            <p style={{ marginBottom: '16px' }}>
                This is a "time evolution" intrinsic to the algebra and the state. It doesn't require a pre-existing
                notion of time. The key theorem: &sigma;<sub>t</sub> maps A to itself (&Delta;<sup>it</sup>A&Delta;<sup>&minus;it</sup> &isin; A).
            </p>

            <h3 style={{ fontSize: '1em', marginTop: '32px' }}>The Bisognano-Wichmann Theorem</h3>
            <p style={{ marginBottom: '16px' }}>
                For a Rindler wedge C in Minkowski spacetime (the region accessible to a uniformly accelerating observer),
                Bisognano and Wichmann proved that the modular Hamiltonian is proportional to the boost generator:
            </p>
            <div className="math-block" style={{ fontSize: '1.1em' }}>
                K<sub>C</sub> = 2&pi; &middot; B<sub>C</sub>
            </div>
            <p style={{ marginBottom: '16px' }}>
                where K<sub>C</sub> = &minus;ln &Delta; is the modular Hamiltonian and B<sub>C</sub> is the Lorentz
                boost generator that preserves the Rindler wedge. The factor of 2&pi; is universal and normalization-independent.
            </p>
            <p style={{ marginBottom: '16px' }}>
                This means: <strong>modular flow IS Lorentz boost</strong>. The "time evolution" generated by the
                modular operator for a Rindler wedge is precisely the geometric flow along the boost Killing vector.
                Time is modular flow.
            </p>

            <h3 style={{ fontSize: '1em', marginTop: '32px' }}>The Thermal Time Hypothesis</h3>
            <p style={{ marginBottom: '16px' }}>
                Connes and Rovelli proposed that the physical time flow experienced by an observer is the modular flow
                of their local state. There is no absolute time; time is relative to the observer's state, just as
                position is relative in special relativity.
            </p>
            <p style={{ marginBottom: '16px' }}>
                In OPH, this is a natural consequence of Axiom A1 (each observer has a patch) and the BW theorem.
                An observer's local time is generated by the modular Hamiltonian of their patch algebra.
            </p>

            <h3 style={{ fontSize: '1em', marginTop: '32px' }}>The Unruh Effect</h3>
            <p style={{ marginBottom: '8px' }}>
                The BW theorem immediately implies the <strong>Unruh effect</strong>: an accelerating observer
                sees the vacuum as a thermal state. The Unruh temperature is:
            </p>
            <div className="math-block" style={{ fontSize: '1.1em' }}>
                T<sub>U</sub> = ℏa / (2&pi;ck<sub>B</sub>)
            </div>
            <p style={{ marginBottom: '16px' }}>
                where a is the proper acceleration. This is not a separate postulate but a theorem: modular flow
                is periodic in imaginary time with period 2&pi;/a, which by the KMS condition means the state is
                thermal at temperature T<sub>U</sub>.
            </p>

            <div className="card" style={{ marginBottom: '24px' }}>
                <h4 style={{ margin: '0 0 12px 0', fontSize: '0.9em', color: 'var(--accent-gold)' }}>
                    Numerical Example
                </h4>
                <p style={{ fontSize: '0.85em', margin: '0 0 8px 0' }}>
                    For an acceleration of a = 10<sup>20</sup> m/s&sup2; (about 10<sup>19</sup> g):
                </p>
                <div className="math-block" style={{ fontSize: '0.85em' }}>
                    T<sub>U</sub> = (1.055 &times; 10<sup>&minus;34</sup> &times; 10<sup>20</sup>) / (2&pi; &times; 3 &times; 10<sup>8</sup> &times; 1.381 &times; 10<sup>&minus;23</sup>) &asymp; 0.4 K
                </div>
                <p style={{ fontSize: '0.8em', color: 'var(--text-muted)', margin: 0 }}>
                    Even at extreme accelerations, the Unruh temperature is tiny. This is why it has not been directly
                    measured, though indirect evidence exists.
                </p>
            </div>

            <Explainer title="The KMS condition and thermal equilibrium">
                <p>
                    The Kubo-Martin-Schwinger (KMS) condition says that a state &omega; is in thermal equilibrium at
                    inverse temperature &beta; with respect to a time evolution &alpha;<sub>t</sub> if the two-point
                    correlators satisfy:
                </p>
                <div className="math-block" style={{ fontSize: '0.85em' }}>
                    &omega;(A &middot; &alpha;<sub>t</sub>(B)) = &omega;(&alpha;<sub>t+i&beta;</sub>(B) &middot; A)
                </div>
                <p>
                    The Tomita-Takesaki theorem guarantees that any faithful normal state satisfies the KMS condition
                    with respect to its own modular flow at &beta; = 1 (in natural units). This means: the state is
                    always "thermal" with respect to its own notion of time. Temperature and time are two sides of the
                    same coin.
                </p>
            </Explainer>

            <Explainer title="Modular Hamiltonian beyond Rindler">
                <p>
                    The BW theorem gives a geometric modular Hamiltonian only for very special cases (Rindler wedges,
                    conformal field theories). In general, the modular Hamiltonian K = &minus;ln &rho; is a complicated
                    non-local operator.
                </p>
                <p>
                    However, for small perturbations around the vacuum, the modular Hamiltonian can be expanded:
                </p>
                <div className="math-block" style={{ fontSize: '0.85em' }}>
                    K = 2&pi; &int; d&Sigma;<sup>a</sup> x<sup>b</sup> T<sub>ab</sub> + O(&delta;&rho;&sup2;)
                </div>
                <p>
                    This linearized modular Hamiltonian involves the stress-energy tensor T<sub>ab</sub> integrated
                    over the entangling surface with a weight proportional to distance from the surface. This is
                    the key step that connects modular flow to Einstein's equations, as shown on the Gravity page.
                </p>
            </Explainer>

            <Explainer title="Connection to the OPH axioms">
                <p>
                    In OPH, modular theory connects to the axioms as follows:
                </p>
                <ul style={{ paddingLeft: '20px', lineHeight: '1.8' }}>
                    <li><strong>A1 (Screen Net):</strong> Each patch P has a von Neumann algebra A(P) and a local state &rho;<sub>P</sub>. Modular theory applies to each (A(P), &rho;<sub>P</sub>) pair.</li>
                    <li><strong>A2 (Overlap Consistency):</strong> Modular flows of overlapping patches must be compatible on the overlap. This constrains the geometry.</li>
                    <li><strong>A3 (Area Bound):</strong> The modular Hamiltonian is bounded by the area operator, linking modular flow to geometry.</li>
                    <li><strong>A4 (Local Markov):</strong> The approximate Markov property ensures the modular Hamiltonian is approximately local, which is needed for the BW-type identification to work.</li>
                </ul>
            </Explainer>
        </div>
    );
}
