export type GlossaryCategory =
    'foundation' |
    'axioms' |
    'gravity' |
    'gauge' |
    'spectrum' |
    'methods' |
    'predictions' |
    'meta';

export type GlossaryEntry = {
    term: string;
    symbol?: string;
    definition: string;
    category: GlossaryCategory;
    usedIn: string[];
    links?: Array<{ label: string; url: string }>;
};

export const GLOSSARY_ENTRIES: GlossaryEntry[] = [
    {
        term: 'Observer Patch Holography',
        symbol: 'OPH',
        definition: 'Framework where fundamental data live on observer-accessible patches of a holographic screen; physical law is the consistency structure of overlapping descriptions.',
        category: 'foundation',
        usedIn: ['Home', 'Synthesis'],
    },
    {
        term: 'Holographic Screen',
        symbol: 'S^2',
        definition: 'Observer-facing regulator geometry chart for support-visible cuts, often represented by a horizon 2-sphere. The microphysics surface does not treat this chart as a literal spherical quantum computer.',
        category: 'foundation',
        usedIn: ['The Screen', 'Entropy'],
    },
    {
        term: 'Sphere Ladder',
        symbol: 'S^0 -> S^1 -> S^2 -> S^3',
        definition: 'Reader-facing OPH role map: seed/readout, recurrence loop, horizon screen or public archive, and reconstructed bulk geometry.',
        category: 'foundation',
        usedIn: ['The Screen', 'Synthesis'],
    },
    {
        term: 'Screen-Sieve',
        symbol: '12-port icosahedral orbit',
        definition: 'Conditional sampling theorem: Euler fixes total charge 12; strict unit splitting and a source-derived selector give twelve central ports on a regular icosahedron.',
        category: 'foundation',
        usedIn: ['The Screen', 'Matter Continuations', 'Synthesis'],
    },
    {
        term: 'Observer',
        symbol: 'O=(P,A(P),rho,R)',
        definition: 'An internal pattern defined by a patch, local algebra, local state, and record set.',
        category: 'foundation',
        usedIn: ['Quantum Mechanics', 'No Objective Reality'],
    },
    {
        term: 'Patch Algebra',
        symbol: 'A(P)',
        definition: 'The von Neumann algebra of observables accessible in patch P.',
        category: 'foundation',
        usedIn: ['The Screen', 'Gauge Symmetry', 'Screen Microphysics'],
    },
    {
        term: 'Consensus Protocol',
        definition: 'Finite patch-net repair picture in which local disagreements are reconciled by accepted overlap repairs and evaluated on the physical quotient.',
        category: 'foundation',
        usedIn: ['Consensus Protocol', 'Synthesis'],
    },
    {
        term: 'Observer Synchronization',
        definition: 'Operational question of how overlap data, records, and repair schedules are mutually consistent across observers in one shared microscopic system.',
        category: 'foundation',
        usedIn: ['Screen Microphysics', 'Consensus Protocol', 'Synthesis'],
    },
    {
        term: 'Overlap Consistency',
        symbol: 'rho1|A12 = rho2|A12',
        definition: 'Shared overlap observables must be assigned the same reduced state by every overlapping patch.',
        category: 'axioms',
        usedIn: ['Axioms', 'Quantum Mechanics'],
    },
    {
        term: 'Axiom A1',
        definition: 'Oriented twelve-port observer screen: finite local carriers, each with twelve primitive central port projections on an oriented icosahedral boundary complex, joined by typed seams and coherent triple overlaps, with an oriented spherical support and refinement tower.',
        category: 'axioms',
        usedIn: ['Axioms', 'The Screen'],
    },
    {
        term: 'Axiom A2',
        definition: 'Observer agreement: the interpretation map from observer-accessible data to operational meaning is natural under every visible overlap restriction, recharting, seam translation, and refinement map on accepted public data.',
        category: 'axioms',
        usedIn: ['Axioms', 'Gauge Symmetry'],
    },
    {
        term: 'Axiom A3',
        definition: 'Conditional maximum randomness: the realized state is the information projection onto the constraint set fixed by the screen architecture and observer agreement, relative to an exact reference family, a state-determining observer cover, and strictly positive exact weights.',
        category: 'axioms',
        usedIn: ['Axioms', 'Entropy'],
    },
    {
        term: 'Gravity Interfaces (Recovery and Generalized Entropy)',
        definition: 'Classified gravity interfaces, not axioms. The collar-recovery clause is exact on the declared central-interface Markov branch; the nonexact Gibbs bound additionally requires uniform strong conditional matrix mixing and a boundary-aware scaling rate.',
        category: 'gravity',
        usedIn: ['Axioms', 'Gravity'],
        links: [{ label: 'Fawzi-Renner (arXiv:1410.0664)', url: 'https://arxiv.org/abs/1410.0664' }],
    },
    {
        term: 'Declared Completions',
        definition: 'Sector statements entered as explicit declarations without derived physical selection: three generations inside the CP-capability and weak-sector window 3 to 5, one Higgs, and no extra light sectors. The finite gauge chain consumes none of them.',
        category: 'axioms',
        usedIn: ['Axioms', 'Standard Model'],
    },
    {
        term: 'Local MaxEnt Branch',
        definition: 'Fixed-regulator information-projection branch selected by Axiom A3 from a nonempty convex feasible family. Cross-refinement optimizer compatibility, strong conditional matrix mixing, and collar CMI decay are separate theorem problems.',
        category: 'axioms',
        usedIn: ['Entropy', 'Gravity'],
    },
    {
        term: 'Gauge-as-Gluing Route',
        definition: 'Route in which overlap identifications are non-unique and induce gauge redundancy on boundary data.',
        category: 'axioms',
        usedIn: ['Gauge Symmetry', 'Standard Model'],
    },
    {
        term: 'Central Defect',
        definition: 'Central obstruction on triple overlaps that feeds the Z6-type structural data in the gauge/matter analysis.',
        category: 'axioms',
        usedIn: ['Matter Continuations', 'Standard Model'],
    },
    {
        term: 'Technical Premise T2',
        definition: 'Controlled refinement/scaling-limit scope clause for the BW/null-modular and smooth physical Einstein branches. It does not govern the exact finite source-poset theorem, the constructed ambient 1+3 Lorentz carrier, or the typed finite Einstein-shape implication; connecting those finite results to a physical manifold and smooth Einstein dynamics requires the full continuum certificate, including tensor-curvature convergence or the independent small-ball/null-balance identification. Scalar-curvature convergence alone is diagnostic.',
        category: 'axioms',
        usedIn: ['Axioms', 'Gravity'],
    },
    {
        term: 'Technical Premise T3',
        definition: 'Fixed-cap generalized-entropy stationarity premise for the Jacobson-type gravity branch.',
        category: 'axioms',
        usedIn: ['Axioms', 'Gravity'],
    },
    {
        term: 'Regulator Premise',
        definition: 'Regulated local algebras are type-I finite-dimensional factors.',
        category: 'methods',
        usedIn: ['Gauge Symmetry', 'Standard Model'],
    },
    {
        term: 'Boundary Fixed-Point Premise',
        definition: 'Region observables are fixed points under boundary gauge action.',
        category: 'methods',
        usedIn: ['Gauge Symmetry', 'Standard Model'],
    },
    {
        term: 'Compact-Gauge Refinement Receipt',
        definition: 'Explicit refinement data supplying finite-state extendability, center-compatible block-multiplicity embeddings, common stagewise strict representatives with coherent surjective boundary-group maps that intertwine them, finite tensor realizations, and compatible forgetful fibers. Compact-gauge colimit reconstruction is conditional on this receipt.',
        category: 'gauge',
        usedIn: ['Axioms', 'Gauge Symmetry', 'Standard Model', 'QFT Boundary', 'Synthesis'],
    },
    {
        term: 'Axiom MX',
        symbol: '||E_z|| <= kappa exp(-(m-r0)/zeta)',
        definition: 'Legacy label for the theorem-local nonexact collar premise: the matrix conditional log-density defect has a boundary-anchor expansion with uniform strong exponential decay. Ordinary two-point clustering, a Lieb-Robinson bound, or a spectral gap does not imply it for a general noncommuting Gibbs state.',
        category: 'methods',
        usedIn: ['Gravity', 'Error Correction'],
    },
    {
        term: 'Central-Interface Collar Branch',
        symbol: 'I(A:D|B)=0',
        definition: 'Declared branch on which the edge split and Markov split align, so collar CMI vanishes exactly without a decay limit or strong-mixing premise.',
        category: 'methods',
        usedIn: ['Gravity', 'Error Correction'],
    },
    {
        term: 'Collar Rate Margin',
        symbol: 'delta/xi - log|partial C|_UV',
        definition: 'Boundary-aware exponent controlling the nonexact collar envelope. It must tend to +infinity for the bound to vanish; delta/l_UV -> infinity alone is insufficient when the UV boundary count grows.',
        category: 'methods',
        usedIn: ['Gravity', 'Error Correction'],
    },
    {
        term: 'Finite Collar Receipt',
        definition: 'Finite-stage proxy recording the interaction contract, separator and boundary count, regional CMI, matrix defect, predeclared mixing constants, held-out coverage, recovery error, and rate margin. A finite receipt does not prove the cofinal scaling limit.',
        category: 'methods',
        usedIn: ['Gravity', 'Error Correction'],
    },
    {
        term: 'Premise LR',
        symbol: 'v_LR',
        definition: 'Lieb-Robinson locality bound controlling operator support growth.',
        category: 'methods',
        usedIn: ['Modular Flow', 'Gravity'],
    },
    {
        term: 'N1/N2/N3',
        definition: 'Null modular bridge conditions connecting modular data to local EFT stress tensor structure.',
        category: 'methods',
        usedIn: ['Gravity', 'Predictions'],
    },
    {
        term: 'Generalized Entropy',
        symbol: 'S_gen = A/4G + S_bulk',
        definition: 'Area and bulk entropy combination varied in entanglement-equilibrium derivations.',
        category: 'gravity',
        usedIn: ['Entropy', 'Gravity'],
    },
    {
        term: 'Raychaudhuri Equation',
        symbol: 'dtheta/dlambda',
        definition: 'Null-congruence focusing law relating expansion to curvature term R_kk.',
        category: 'gravity',
        usedIn: ['Gravity'],
    },
    {
        term: 'Entanglement Equilibrium',
        symbol: 'delta S_gen = 0',
        definition: 'Stationarity condition of generalized entropy under allowed local variations.',
        category: 'gravity',
        usedIn: ['Gravity'],
    },
    {
        term: 'Jacobson-type Einstein Relation',
        symbol: 'R_kk = 8pi G T_kk',
        definition: 'Legacy explainer shorthand for the local rest-frame relation in the gravity branch; the papers state a Jacobson-type Einstein relation with a tensor upgrade modulo the metric ambiguity.',
        category: 'gravity',
        usedIn: ['Gravity'],
    },
    {
        term: 'Einstein Equation',
        symbol: 'G_ab + Lambda g_ab = 8pi G<T_ab>',
        definition: 'Tensor completion of the conditional null branch. Fixing the remaining Lambda term requires a source-selected cosmic capacity, a same-invariant bridge, and horizon-record saturation.',
        category: 'gravity',
        usedIn: ['Gravity', 'De Sitter'],
    },
    {
        term: 'Cosmological Constant from Capacity',
        symbol: 'Lambda_CRC = 3pi/(G N_CRC)',
        definition: 'Conditional horizon relation. It becomes physical only after a source-selected N is identified with the same invariant counted by the global readback. Measured Lambda supplies the retrospective Planck base-LambdaCDM comparison coordinate 3.31292709806038e122.',
        category: 'gravity',
        usedIn: ['De Sitter', 'Matter Continuations'],
    },
    {
        term: 'de Sitter Radius',
        symbol: 'r_dS = sqrt(3/Lambda)',
        definition: 'Horizon radius of asymptotic positive-Lambda spacetime.',
        category: 'gravity',
        usedIn: ['De Sitter', 'Predictions'],
    },
    {
        term: 'Conformal-Lorentz Isomorphism',
        symbol: 'Conf^+(S^2) ~ SO^+(3,1)',
        definition: 'Screen conformal group isomorphic to connected Lorentz group.',
        category: 'gravity',
        usedIn: ['Lorentz'],
    },
    {
        term: 'Modular Flow',
        symbol: 'sigma_t(A)=Delta^{it}A Delta^{-it}',
        definition: 'Tomita-Takesaki automorphism flow associated with a chosen state and region.',
        category: 'gravity',
        usedIn: ['Modular Flow', 'Gravity'],
    },
    {
        term: 'Bisognano-Wichmann',
        symbol: 'K = 2pi B',
        definition: 'Continuum BW template. In the OPH papers, geometric modular flow is stated on the explicit BW branch at the automorphism level, with K = 2pi B only in the special type-I realization.',
        category: 'gravity',
        usedIn: ['Modular Flow', 'Gravity'],
    },
    {
        term: 'Unruh Temperature',
        symbol: 'T = hbar a / 2pi c k_B',
        definition: 'Thermal response of accelerated observers, used in local Clausius identifications.',
        category: 'gravity',
        usedIn: ['Modular Flow', 'Gravity'],
    },
    {
        term: 'Gauge-as-Gluing',
        definition: 'Gauge redundancy interpreted as overlap frame-change freedom.',
        category: 'gauge',
        usedIn: ['Gauge Symmetry', 'Standard Model'],
    },
    {
        term: 'Edge Sector',
        definition: 'Boundary/collar superselection sector carrying representation data.',
        category: 'gauge',
        usedIn: ['Gauge Symmetry', 'Standard Model'],
    },
    {
        term: 'Edge-Center Completion',
        symbol: 'EC',
        definition: 'Collar decomposition where center labels become explicit classical sectors.',
        category: 'gauge',
        usedIn: ['Gauge Symmetry', 'Error Correction'],
    },
    {
        term: 'Heat-Kernel Sector Law',
        symbol: 'p_R propto d_R exp(-t C2)',
        definition: 'MaxEnt distribution over representations weighted by dimension and Casimir.',
        category: 'gauge',
        usedIn: ['Standard Model', 'Matter Continuations'],
        links: [{ label: 'Heat kernel (Wikipedia)', url: 'https://en.wikipedia.org/wiki/Heat_kernel' }],
    },
    {
        term: 'Tannaka-Krein Reconstruction',
        definition: 'Reconstructs a compact group as the unitary symmetric monoidal automorphism group Aut_tensor(F) of a faithful finite-dimensional fiber functor on a rigid symmetric C*-tensor category; the category need not have finitely many simple objects.',
        category: 'gauge',
        usedIn: ['Gauge Symmetry', 'Standard Model'],
        links: [{ label: 'Tannaka-Krein duality', url: 'https://en.wikipedia.org/wiki/Tannaka%E2%80%93Krein_duality' }],
    },
    {
        term: 'Doplicher-Roberts Reconstruction',
        symbol: 'DR',
        definition: 'Categorical reconstruction in localized transportable sector settings.',
        category: 'gauge',
        usedIn: ['Standard Model'],
        links: [{ label: 'Doplicher-Roberts theorem overview', url: 'https://ncatlab.org/nlab/show/Doplicher-Roberts+duality' }],
    },
    {
        term: 'Loop-Coherent Gluing',
        symbol: '[z]=0, Hol=1',
        definition: 'Combined transport test: the central triangle class vanishes or the noncentral higher associator strictifies, and at least one allowed strict edge 1-cocycle representative has trivial represented holonomy around every closed overlap loop.',
        category: 'gauge',
        usedIn: ['Axioms', 'Gauge Symmetry', 'Standard Model'],
        links: [{ label: 'Selection and transportability notes', url: '/standard-model' }],
    },
    {
        term: 'Admissibility Conditions',
        definition: 'Sector filters: transportable, anomaly-free, chiral-stable, single-Higgs, CP-capable, weak UV-completable.',
        category: 'gauge',
        usedIn: ['Gauge Symmetry', 'Standard Model', 'QFT Boundary'],
        links: [{ label: 'Admissibility simulator', url: '/standard-model' }],
    },
    {
        term: 'Declared Sector Completions',
        definition: 'The three-generation, one-Higgs, and no-extra-light-sector statements enter as declarations without derived physical selection after the admissibility filters; they are classifications of the realized sector, not a dynamics law and not an axiom.',
        category: 'gauge',
        usedIn: ['Axioms', 'Gauge Symmetry', 'Standard Model', 'QFT Boundary', 'Synthesis'],
        links: [
            { label: 'Gauge derivation walkthrough', url: '/standard-model' },
            { label: 'Paper (Zenodo)', url: 'https://doi.org/10.5281/zenodo.18288114' },
        ],
    },
    {
        term: 'Faithful Edge Capacity',
        symbol: 'chi_faith',
        definition: 'Dimension of minimal faithful unitary representation carrying all gauge factors.',
        category: 'gauge',
        usedIn: ['Standard Model'],
    },
    {
        term: 'Standard Model Quotient',
        symbol: '[SU(3)xSU(2)xU(1)]/Z6',
        definition: 'Maximal faithful image of the declared fifteen-state matter fixture after quotienting by its common Z6 kernel. Physical global-form selection requires a complete character lattice and a same-source loop-to-kernel identification.',
        category: 'gauge',
        usedIn: ['Standard Model'],
    },
    {
        term: 'Witten SU(2) Anomaly Constraint',
        symbol: 'N_c + 1 even',
        definition: 'Global anomaly condition forcing odd N_c under SM-like doublet counting.',
        category: 'gauge',
        usedIn: ['Standard Model'],
    },
    {
        term: 'Intrinsic CKM CP Phases',
        symbol: '(N_g-1)(N_g-2)/2',
        definition: 'Generation-count lower bound from requiring physical CP violation.',
        category: 'gauge',
        usedIn: ['Standard Model'],
    },
    {
        term: 'Asymptotic Freedom Bound',
        symbol: '22 - N_g(N_c+1) > 0',
        definition: 'Weak-sector one-loop UV-completability inequality limiting generation count.',
        category: 'gauge',
        usedIn: ['Standard Model'],
    },
    {
        term: 'Pixel Constant',
        symbol: 'P = a_cell/l_P^2',
        definition: 'A declared local map can have a certified root. A physical pixel value additionally needs target-independent map selection, proof that both sides read the same quantity, and same-scheme endpoint transport.',
        category: 'spectrum',
        usedIn: ['Matter Continuations', 'Synthesis'],
    },
    {
        term: 'Cosmic Record Capacity',
        symbol: 'N = log M0(U_N)',
        definition: 'Direct closure proposal: a universe supplied with logarithmic capacity N reads back the logarithm of its correctable public-record count. Self-reference forces equality only after both readings are proved to denote the same typed invariant. An exact bounded all-rung generation-register counterfamily is non-identifying. Universal membership in the complete A1–A3 source contract is unproved, so direct N is not evaluable and emits no cosmic value.',
        category: 'spectrum',
        usedIn: ['Matter Continuations', 'De Sitter', 'Synthesis'],
    },
    {
        term: 'Capacity-Electroweak Bridge',
        symbol: 'v/E_cell = (N_EW/pi)^(-P*/12)',
        definition: 'The measured-endpoint branch gives N_EW(P_C)=3.5323546226929907e122 at P_C=1.630968209403959. The distinct source-forward branch gives N0(P_fwd)=3.532131543418936e122 at P_fwd=1.630972095858897. Total reserve P_fwd/4 and six-class equidistribution give one-class presence P_fwd/24. Physical one-class selection and a global survival action would give N_presence=N0(1-P_fwd/24)=3.292097877326465e122; the Poisson alternative needs extra mean-count structure. Exact positive composition countermodels select neither global action nor a blocked-event semantics from the declared finite-cut attachment class. The named-law branch is not evaluable on that class, its horizon branch has no source-selected positive capacity carrier, and neither numerical row is predictive. A positive branch requires a stronger target-independent source law.',
        category: 'spectrum',
        usedIn: ['Matter Continuations', 'Synthesis'],
    },
    {
        term: 'Unification Scale',
        symbol: 'M_U = E_P e^{-2pi} P^{1/6}',
        definition: 'Derived UV scale entering running-coupling pipeline.',
        category: 'spectrum',
        usedIn: ['Matter Continuations', 'Unification'],
    },
    {
        term: 'Unified Coupling',
        symbol: 'alpha_U',
        definition: 'Finite-screen unified gauge-width coupling solved from pixel-constraint closure.',
        category: 'spectrum',
        usedIn: ['Matter Continuations'],
    },
    {
        term: 'Pixel Constraint',
        symbol: 'P/4 = lbar_SU2 + lbar_SU3',
        definition: 'Entropy matching equation used to solve alpha_U self-consistently.',
        category: 'spectrum',
        usedIn: ['Matter Continuations'],
    },
    {
        term: 'Z6 Defect Suppression',
        symbol: 'epsilon = 1/6',
        definition: 'Conditional suppression factor attached to the declared order-six quotient. Its physical use requires a global-form selection that is not derived.',
        category: 'spectrum',
        usedIn: ['Matter Continuations', 'Standard Model'],
    },
    {
        term: 'Koide Continuation Phase',
        symbol: 'delta = 2/9',
        definition: 'Frozen phenomenological phase used by the charged-lepton continuation. OPH dynamics does not derive it as a generation-space holonomy.',
        category: 'spectrum',
        usedIn: ['Matter Continuations'],
    },
    {
        term: 'Icosahedral Face-Corner Carrier',
        symbol: 'A5/C3',
        definition: 'Exact OPH screen geometry in which each outward-oriented icosahedral face has a local three-corner cyclic fiber. The sixty global face-corner flags do not canonically select one physical charged-family space. A conditional weight theorem and engineered digital CFQ model close formal schema consistency, not OPH dynamical or physical charged-sector selection.',
        category: 'spectrum',
        usedIn: ['Matter Continuations', 'Standard Model'],
    },
    {
        term: 'CFQ Digital Carrier',
        symbol: 'CFQ1-CFQ8 fixture',
        definition: 'Engineered finite software model of the stipulated charged face-quotient register and path schema. It verifies reciprocal trace arithmetic, a central accepted/rejected record dilation, A5 graph covariance, and inert stabilization. Its dimensions, automaton, grading, clock, and response are authored; it derives no physical charged-source selection.',
        category: 'spectrum',
        usedIn: ['Matter Continuations', 'Standard Model'],
    },
    {
        term: 'Texture Exponents',
        symbol: 'n_u,n_d,n_e',
        definition: 'Integer hierarchy labels controlling power-law suppression of Yukawas.',
        category: 'spectrum',
        usedIn: ['Matter Continuations'],
    },
    {
        term: 'Massless Symmetry-Protected Zeros',
        symbol: 'm_gamma=m_g=m_graviton=0',
        definition: 'Classical carrier mass terms excluded on the declared Maxwell, Yang-Mills, and Einstein action branches; no quantum pole theorem is implied.',
        category: 'predictions',
        usedIn: ['Standard Model', 'Predictions'],
    },
    {
        term: 'No Simple-GUT X/Y Channel',
        definition: 'The product adjoint excludes X/Y leptoquark generators; other baryon-violating mechanisms are separate.',
        category: 'predictions',
        usedIn: ['Standard Model', 'Predictions'],
    },
    {
        term: 'GW Horizon Comb',
        symbol: 'x_k = ln(k)/(8pi)',
        definition: 'Continuation-level ringdown template after mass-spin rescaling, outside the recovered core. The uniform-offset alpha = 4 branch fails its own assumptions.',
        category: 'predictions',
        usedIn: ['Predictions'],
    },
    {
        term: 'MOND-Scale Relation',
        symbol: 'a0 ~ c^2 sqrt(Lambda)',
        definition: 'Infrared benchmark scale tied to positive cosmological constant. The paper surface presents suggestive numerics and does not derive a full galaxy-response law.',
        category: 'predictions',
        usedIn: ['Dark Matter', 'Predictions'],
    },
    {
        term: 'No Global Symmetries',
        definition: 'Exact global symmetries are absent in full gauge/gravity patch framework.',
        category: 'predictions',
        usedIn: ['Gauge Symmetry', 'Synthesis'],
    },
    {
        term: 'String Bridge',
        symbol: '2D YM heat kernels',
        definition: 'Edge-sector heat-kernel ensemble equals 2D Yang-Mills partition structure with large-N worldsheet expansion.',
        category: 'predictions',
        usedIn: ['Unification', 'Synthesis'],
    },
    {
        term: 'Strange-Loop Closure',
        symbol: 'Phi(x*) = x*',
        definition: 'Fixed-point explanatory closure connecting observer-compatible physics and observer emergence/reconstruction.',
        category: 'meta',
        usedIn: ['Synthesis'],
    },
    {
        term: 'Intersubjective Reality',
        definition: 'Reality is the overlap-consistent content of patch descriptions, without an external observer-independent state description.',
        category: 'meta',
        usedIn: ['No Objective Reality', 'Synthesis'],
    },
    {
        term: 'Records',
        symbol: 'R',
        definition: 'Stable, shareable patch-internal correlations defining effective measurement outcomes.',
        category: 'methods',
        usedIn: ['Quantum Mechanics', 'Error Correction'],
    },
    {
        term: 'Recovery Map',
        symbol: 'R_{B->BC}',
        definition: 'Fawzi-Renner CPTP map producing a recovered comparison state when CMI is small. Exact Markov splice identities require the separate exact or controlled-limit conditions and Markov-split alignment.',
        category: 'methods',
        usedIn: ['Error Correction', 'Gravity'],
    },
    {
        term: 'Inconsistency Potential',
        symbol: 'Phi',
        definition: 'Total mismatch functional over overlaps on the finite patch net. Accepted repairs must lower the touched-overlap contribution on the declared branch.',
        category: 'methods',
        usedIn: ['Consensus Protocol'],
    },
    {
        term: 'Lyapunov Functional',
        definition: 'Quantity that decreases along the accepted repair dynamics, ensuring termination on the finite patch net when the local-fit contract is enforced.',
        category: 'methods',
        usedIn: ['Consensus Protocol'],
    },
    {
        term: 'Normal Form',
        definition: 'Repair-fixed patch-net state reached from a specified source after accepted local reconciliations are exhausted. Under the stated completeness and gluing assumptions it is independent of the repair schedule from that source; comparing different sources requires a separate observation-fiber condition.',
        category: 'methods',
        usedIn: ['Consensus Protocol'],
    },
    {
        term: 'Observation Fiber',
        symbol: 'C_b',
        definition: 'Consistent states sharing one protected observation b. An empty fiber is unrealizable, a singleton fiber is reconstructing, and a fiber with multiple inequivalent states is ambiguous.',
        category: 'methods',
        usedIn: ['Consensus Protocol'],
    },
    {
        term: 'Observation-Determined Normal Form',
        definition: 'A consistent endpoint determined by protected observation data, modulo the declared silent or gauge equivalence. This is stronger than same-source confluence and does not by itself supply normalization or liveness.',
        category: 'methods',
        usedIn: ['Consensus Protocol'],
    },
    {
        term: 'Cross-Source Identification',
        definition: 'Agreement of normal endpoints reached from possibly different sources with the same protected observation. Under observation preservation and normal-form completeness, it is equivalent to the observation identifying the consistent quotient.',
        category: 'methods',
        usedIn: ['Consensus Protocol'],
    },
    {
        term: 'Holonomy Obstruction',
        definition: 'Global cycle defect showing that pairwise-compatible overlap data can fail to extend to a single globally consistent configuration.',
        category: 'methods',
        usedIn: ['Consensus Protocol'],
    },
    {
        term: 'Record Algebra',
        definition: 'Observer-accessible algebra generated by exact central record projectors or quantitatively stable approximately commuting surrogates on the fixed-cutoff branch.',
        category: 'methods',
        usedIn: ['Consensus Protocol', 'Screen Microphysics'],
    },
    {
        term: 'Checkpoint / Restoration',
        definition: 'Microphysical backup-and-recovery mechanism used to stabilize records and observer-level state across local repair and synchronization events.',
        category: 'methods',
        usedIn: ['Screen Microphysics'],
    },
    {
        term: 'Federated Patch-Carrier Architecture',
        definition: 'Chosen fixed-cutoff microphysics model with federated finite patches, echosahedral multi-port interfaces, records, overlap observables, and repair dynamics.',
        category: 'methods',
        usedIn: ['Screen Microphysics'],
    },
    {
        term: 'Conditional Mutual Information',
        symbol: 'I(A:D|B)',
        definition: 'Scalar separator measure controlling recoverability and Markov quality. It has no tensor indices and is not, by itself, a stress tensor, local energy density, or dark-sector source.',
        category: 'methods',
        usedIn: ['Entropy', 'Error Correction', 'Gravity'],
    },
    {
        term: 'KMS Condition',
        symbol: 'omega(A alpha_t(B)) = omega(alpha_{t+i beta}(B)A)',
        definition: 'Thermal equilibrium characterization with respect to modular flow.',
        category: 'methods',
        usedIn: ['Modular Flow'],
        links: [{ label: 'KMS state (Wikipedia)', url: 'https://en.wikipedia.org/wiki/KMS_state' }],
    },
    {
        term: 'Peter-Weyl Decomposition',
        symbol: 'L^2(G)=sum_R V_R tensor V_R*',
        definition: 'Group harmonic analysis decomposition underlying edge-mode multiplicity and beta-shift effects.',
        category: 'methods',
        usedIn: ['Unification', 'Standard Model'],
        links: [{ label: 'Peter-Weyl theorem', url: 'https://en.wikipedia.org/wiki/Peter%E2%80%93Weyl_theorem' }],
    },
    {
        term: 'Edge Beta Shift',
        symbol: 'Delta b',
        definition: 'Difference between edge-corrected and SM one-loop beta coefficients, used to model OPH edge-sector vacuum-polarization effects.',
        category: 'gauge',
        usedIn: ['Unification', 'Matter Continuations'],
    },
    {
        term: 'One-Loop Running Law',
        symbol: 'alpha_i^-1(mu)=alpha_U^-1+(b_i/2pi)ln(M_U/mu)',
        definition: 'Leading renormalization-group relation used to evolve gauge couplings from unification scale to lower energies.',
        category: 'methods',
        usedIn: ['Unification', 'Matter Continuations'],
    },
    {
        term: 'Threshold Corrections',
        symbol: 'Delta_th',
        definition: 'Finite matching contributions at mass thresholds or scheme changes that perturb pure one-loop running predictions.',
        category: 'methods',
        usedIn: ['Unification', 'Matter Continuations', 'Synthesis'],
        links: [{ label: 'Renormalization group matching', url: 'https://en.wikipedia.org/wiki/Renormalization_group' }],
    },
    {
        term: 'No-Cheat Audit',
        symbol: 'Input contract',
        definition: 'Methodological check that the prediction pipeline depends only on declared inputs, derived structures, and explicitly unproved theorem targets.',
        category: 'meta',
        usedIn: ['Matter Continuations', 'Synthesis'],
    },
];
