export type GlossaryCategory =
    'foundation' |
    'axioms' |
    'gravity' |
    'gauge' |
    'spectrum' |
    'methods' |
    'predictions' |
    'meta';

export type GlossaryEntry = {
    term: string;
    symbol?: string;
    definition: string;
    category: GlossaryCategory;
    usedIn: string[];
    links?: Array<{ label: string; url: string }>;
};

export const GLOSSARY_ENTRIES: GlossaryEntry[] = [
    {
        term: 'Observer Patch Holography',
        symbol: 'OPH',
        definition: 'Framework where fundamental data live on observer-accessible patches of a holographic screen; physical law is the consistency structure of overlapping descriptions.',
        category: 'foundation',
        usedIn: ['Home', 'Synthesis'],
    },
    {
        term: 'Holographic Screen',
        symbol: 'S^2',
        definition: 'The horizon 2-sphere carrying the algebra net. Bulk spacetime is emergent from the screen state and patch relations.',
        category: 'foundation',
        usedIn: ['The Screen', 'Entropy'],
    },
    {
        term: 'Observer',
        symbol: 'O=(P,A(P),rho,R)',
        definition: 'An internal pattern defined by a patch, local algebra, local state, and record set.',
        category: 'foundation',
        usedIn: ['Quantum Mechanics', 'No Objective Reality'],
    },
    {
        term: 'Patch Algebra',
        symbol: 'A(P)',
        definition: 'The von Neumann algebra of observables accessible in patch P.',
        category: 'foundation',
        usedIn: ['The Screen', 'Gauge Symmetry', 'Screen Microphysics'],
    },
    {
        term: 'Consensus Protocol',
        definition: 'Finite patch-net repair picture in which local disagreements are reconciled by accepted overlap repairs and evaluated on the physical quotient.',
        category: 'foundation',
        usedIn: ['Consensus Protocol', 'Synthesis'],
    },
    {
        term: 'Observer Synchronization',
        definition: 'Operational question of how overlap data, records, and repair schedules remain mutually consistent across observers in one shared microscopic system.',
        category: 'foundation',
        usedIn: ['Screen Microphysics', 'Consensus Protocol', 'Synthesis'],
    },
    {
        term: 'Overlap Consistency',
        symbol: 'rho1|A12 = rho2|A12',
        definition: 'Shared overlap observables must be assigned the same reduced state by every overlapping patch.',
        category: 'axioms',
        usedIn: ['Axioms', 'Quantum Mechanics'],
    },
    {
        term: 'Axiom A1',
        definition: 'Screen-net axiom: connected subregions of S^2 are assigned algebras in an isotonic net.',
        category: 'axioms',
        usedIn: ['Axioms', 'The Screen'],
    },
    {
        term: 'Axiom A2',
        definition: 'Overlap-consistency axiom: local descriptions must agree on shared overlap algebras.',
        category: 'axioms',
        usedIn: ['Axioms', 'Gauge Symmetry'],
    },
    {
        term: 'Axiom A3',
        definition: 'Local MaxEnt and refinement-stability axiom selecting one common finite-dimensional local-constraint family across refinement.',
        category: 'axioms',
        usedIn: ['Axioms', 'Entropy'],
    },
    {
        term: 'Axiom A4',
        definition: 'Recoverable generalized-entropy axiom supplying the entropy/recoverability structure used in the collar and gravity branches.',
        category: 'axioms',
        usedIn: ['Axioms', 'Gravity'],
        links: [{ label: 'Fawzi-Renner (arXiv:1410.0664)', url: 'https://arxiv.org/abs/1410.0664' }],
    },
    {
        term: 'Axiom A5 / MAR',
        definition: 'Minimal Admissible Realization: lexicographic selector on admissible gauge-sector packages.',
        category: 'axioms',
        usedIn: ['Axioms', 'Standard Model'],
    },
    {
        term: 'Local MaxEnt Branch',
        definition: 'Finite local-constraint branch selected by Axiom A3, supplying the local-Gibbs and refinement-stable state family used in later arguments.',
        category: 'axioms',
        usedIn: ['Entropy', 'Gravity'],
    },
    {
        term: 'Gauge-as-Gluing Route',
        definition: 'Route in which overlap identifications are non-unique and induce gauge redundancy on boundary data.',
        category: 'axioms',
        usedIn: ['Gauge Symmetry', 'Standard Model'],
    },
    {
        term: 'Central Defect',
        definition: 'Central obstruction on triple overlaps that feeds the Z6-type structural data in the gauge/matter analysis.',
        category: 'axioms',
        usedIn: ['Matter Continuations', 'Standard Model'],
    },
    {
        term: 'Technical Premise T2',
        definition: 'Controlled refinement/scaling-limit scope clause for Lorentz, null-modular, and Einstein statements.',
        category: 'axioms',
        usedIn: ['Axioms', 'Gravity'],
    },
    {
        term: 'Technical Premise T3',
        definition: 'Fixed-cap generalized-entropy stationarity premise for the Jacobson-type gravity branch.',
        category: 'axioms',
        usedIn: ['Axioms', 'Gravity'],
    },
    {
        term: 'Premise R0',
        definition: 'Regulated local algebras are type-I finite-dimensional factors.',
        category: 'methods',
        usedIn: ['Gauge Symmetry', 'Standard Model'],
    },
    {
        term: 'Premise R1',
        definition: 'Region observables are fixed points under boundary gauge action.',
        category: 'methods',
        usedIn: ['Gauge Symmetry', 'Standard Model'],
    },
    {
        term: 'Axiom MX',
        definition: 'Exponential mixing of conditional mutual information across collars.',
        category: 'methods',
        usedIn: ['Gravity', 'Error Correction'],
    },
    {
        term: 'Premise LR',
        symbol: 'v_LR',
        definition: 'Lieb-Robinson locality bound controlling operator support growth.',
        category: 'methods',
        usedIn: ['Modular Flow', 'Gravity'],
    },
    {
        term: 'N1/N2/N3',
        definition: 'Null modular bridge conditions connecting modular data to local EFT stress tensor structure.',
        category: 'methods',
        usedIn: ['Gravity', 'Predictions'],
    },
    {
        term: 'Generalized Entropy',
        symbol: 'S_gen = A/4G + S_bulk',
        definition: 'Area and bulk entropy combination varied in entanglement-equilibrium derivations.',
        category: 'gravity',
        usedIn: ['Entropy', 'Gravity'],
    },
    {
        term: 'Raychaudhuri Equation',
        symbol: 'dtheta/dlambda',
        definition: 'Null-congruence focusing law relating expansion to curvature term R_kk.',
        category: 'gravity',
        usedIn: ['Gravity'],
    },
    {
        term: 'Entanglement Equilibrium',
        symbol: 'delta S_gen = 0',
        definition: 'Stationarity condition of generalized entropy under allowed local variations.',
        category: 'gravity',
        usedIn: ['Gravity'],
    },
    {
        term: 'Jacobson-type Einstein Relation',
        symbol: 'R_kk = 8pi G T_kk',
        definition: 'Legacy explainer shorthand for the local rest-frame relation in the gravity branch; the papers state a Jacobson-type Einstein relation with a tensor upgrade modulo the metric ambiguity.',
        category: 'gravity',
        usedIn: ['Gravity'],
    },
    {
        term: 'Einstein Equation',
        symbol: 'G_ab + Lambda g_ab = 8pi G<T_ab>',
        definition: 'Tensor completion of null closure, with Lambda fixed only after global input.',
        category: 'gravity',
        usedIn: ['Gravity', 'De Sitter'],
    },
    {
        term: 'Cosmological Constant from Capacity',
        symbol: 'Lambda = 3pi/(G log dim H_tot)',
        definition: 'Global closure equation tying Lambda to finite screen Hilbert-space capacity.',
        category: 'gravity',
        usedIn: ['De Sitter', 'Matter Continuations'],
    },
    {
        term: 'de Sitter Radius',
        symbol: 'r_dS = sqrt(3/Lambda)',
        definition: 'Horizon radius of asymptotic positive-Lambda spacetime.',
        category: 'gravity',
        usedIn: ['De Sitter', 'Predictions'],
    },
    {
        term: 'Conformal-Lorentz Isomorphism',
        symbol: 'Conf^+(S^2) ~ SO^+(3,1)',
        definition: 'Screen conformal group isomorphic to connected Lorentz group.',
        category: 'gravity',
        usedIn: ['Lorentz'],
    },
    {
        term: 'Modular Flow',
        symbol: 'sigma_t(A)=Delta^{it}A Delta^{-it}',
        definition: 'Tomita-Takesaki automorphism flow associated with a chosen state and region.',
        category: 'gravity',
        usedIn: ['Modular Flow', 'Gravity'],
    },
    {
        term: 'Bisognano-Wichmann',
        symbol: 'K = 2pi B',
        definition: 'Continuum BW template. In the OPH papers, geometric modular flow is stated on the explicit BW branch at the automorphism level, with K = 2pi B only in the special type-I realization.',
        category: 'gravity',
        usedIn: ['Modular Flow', 'Gravity'],
    },
    {
        term: 'Unruh Temperature',
        symbol: 'T = hbar a / 2pi c k_B',
        definition: 'Thermal response of accelerated observers, used in local Clausius identifications.',
        category: 'gravity',
        usedIn: ['Modular Flow', 'Gravity'],
    },
    {
        term: 'Gauge-as-Gluing',
        definition: 'Gauge redundancy interpreted as overlap frame-change freedom.',
        category: 'gauge',
        usedIn: ['Gauge Symmetry', 'Standard Model'],
    },
    {
        term: 'Edge Sector',
        definition: 'Boundary/collar superselection sector carrying representation data.',
        category: 'gauge',
        usedIn: ['Gauge Symmetry', 'Standard Model'],
    },
    {
        term: 'Edge-Center Completion',
        symbol: 'EC',
        definition: 'Collar decomposition where center labels become explicit classical sectors.',
        category: 'gauge',
        usedIn: ['Gauge Symmetry', 'Error Correction'],
    },
    {
        term: 'Heat-Kernel Sector Law',
        symbol: 'p_R propto d_R exp(-t C2)',
        definition: 'MaxEnt distribution over representations weighted by dimension and Casimir.',
        category: 'gauge',
        usedIn: ['Standard Model', 'Matter Continuations'],
        links: [{ label: 'Heat kernel (Wikipedia)', url: 'https://en.wikipedia.org/wiki/Heat_kernel' }],
    },
    {
        term: 'Tannaka-Krein Reconstruction',
        definition: 'Reconstructs compact group from representation/fusion category data.',
        category: 'gauge',
        usedIn: ['Gauge Symmetry', 'Standard Model'],
        links: [{ label: 'Tannaka-Krein duality', url: 'https://en.wikipedia.org/wiki/Tannaka%E2%80%93Krein_duality' }],
    },
    {
        term: 'Doplicher-Roberts Reconstruction',
        symbol: 'DR',
        definition: 'Categorical reconstruction in localized transportable sector settings.',
        category: 'gauge',
        usedIn: ['Standard Model'],
        links: [{ label: 'Doplicher-Roberts theorem overview', url: 'https://ncatlab.org/nlab/show/Doplicher-Roberts+duality' }],
    },
    {
        term: 'Loop-Coherent Gluing',
        symbol: '[z]=0',
        definition: 'Vanishing loop obstruction class enforcing transportable sector gluing across overlaps.',
        category: 'gauge',
        usedIn: ['Axioms', 'Gauge Symmetry', 'Standard Model'],
        links: [{ label: 'Selection and transportability notes', url: '/standard-model' }],
    },
    {
        term: 'Admissibility Conditions',
        definition: 'Sector filters: transportable, anomaly-free, chiral-stable, single-Higgs, CP-capable, weak UV-completable.',
        category: 'gauge',
        usedIn: ['Gauge Symmetry', 'Standard Model', 'QFT Emerges'],
        links: [{ label: 'Admissibility simulator', url: '/standard-model' }],
    },
    {
        term: 'Selection Axiom MAR',
        symbol: 'C(Sigma)=(chi_faith,N_nonab,N_c,N_g)',
        definition: 'Minimal Admissible Realization: select lexicographically minimal C(Sigma) only after admissibility filters; a selection rule distinct from a dynamics law.',
        category: 'gauge',
        usedIn: ['Axioms', 'Gauge Symmetry', 'Standard Model', 'QFT Emerges', 'Synthesis'],
        links: [
            { label: 'Gauge derivation walkthrough', url: '/standard-model' },
            { label: 'Paper (Zenodo)', url: 'https://doi.org/10.5281/zenodo.18288114' },
        ],
    },
    {
        term: 'Faithful Edge Capacity',
        symbol: 'chi_faith',
        definition: 'Dimension of minimal faithful unitary representation carrying all gauge factors.',
        category: 'gauge',
        usedIn: ['Standard Model'],
    },
    {
        term: 'Standard Model Quotient',
        symbol: '[SU(3)xSU(2)xU(1)]/Z6',
        definition: 'Global gauge group after modding out the trivially acting shared center.',
        category: 'gauge',
        usedIn: ['Standard Model'],
    },
    {
        term: 'Witten SU(2) Anomaly Constraint',
        symbol: 'N_c + 1 even',
        definition: 'Global anomaly condition forcing odd N_c under SM-like doublet counting.',
        category: 'gauge',
        usedIn: ['Standard Model'],
    },
    {
        term: 'Intrinsic CKM CP Phases',
        symbol: '(N_g-1)(N_g-2)/2',
        definition: 'Generation-count lower bound from requiring physical CP violation.',
        category: 'gauge',
        usedIn: ['Standard Model'],
    },
    {
        term: 'Asymptotic Freedom Bound',
        symbol: '22 - N_g(N_c+1) > 0',
        definition: 'Weak-sector one-loop UV-completability inequality limiting generation count.',
        category: 'gauge',
        usedIn: ['Standard Model'],
    },
    {
        term: 'Pixel Constant',
        symbol: 'P = a_cell/l_P^2',
        definition: 'Primary external input controlling UV cell scale, entropy target, and gauge-closure solution.',
        category: 'spectrum',
        usedIn: ['Matter Continuations', 'Synthesis'],
    },
    {
        term: 'Screen Capacity',
        symbol: 'log(dim H_tot)',
        definition: 'Global input controlling cosmological constant and neutrino/cosmology scales.',
        category: 'spectrum',
        usedIn: ['Matter Continuations', 'De Sitter', 'Synthesis'],
    },
    {
        term: 'Unification Scale',
        symbol: 'M_U = E_P e^{-2pi} P^{1/6}',
        definition: 'Derived UV scale entering running-coupling pipeline.',
        category: 'spectrum',
        usedIn: ['Matter Continuations', 'Unification'],
    },
    {
        term: 'Unified Coupling',
        symbol: 'alpha_U',
        definition: 'Single coupling solved from pixel-constraint closure.',
        category: 'spectrum',
        usedIn: ['Matter Continuations'],
    },
    {
        term: 'Pixel Constraint',
        symbol: 'P/4 = lbar_SU2 + lbar_SU3',
        definition: 'Entropy matching equation used to solve alpha_U self-consistently.',
        category: 'spectrum',
        usedIn: ['Matter Continuations'],
    },
    {
        term: 'Z6 Defect Suppression',
        symbol: 'epsilon = 1/6',
        definition: 'Topological suppression factor from the order-six central quotient.',
        category: 'spectrum',
        usedIn: ['Matter Continuations', 'Standard Model'],
    },
    {
        term: 'Koide Phase',
        symbol: 'delta = 2/9',
        definition: 'Derived generation-space phase entering lepton-structure relations.',
        category: 'spectrum',
        usedIn: ['Matter Continuations'],
    },
    {
        term: 'Texture Exponents',
        symbol: 'n_u,n_d,n_e',
        definition: 'Integer hierarchy labels controlling power-law suppression of Yukawas.',
        category: 'spectrum',
        usedIn: ['Matter Continuations'],
    },
    {
        term: 'Massless Symmetry-Protected Zeros',
        symbol: 'm_gamma=m_g=m_graviton=0',
        definition: 'Exact masses forbidden by emergent gauge/diffeomorphism symmetry structure.',
        category: 'predictions',
        usedIn: ['Standard Model', 'Predictions'],
    },
    {
        term: 'No Gauge-Mediated Proton Decay',
        definition: 'Product-group closure excludes X/Y leptoquark gauge bosons of simple GUTs.',
        category: 'predictions',
        usedIn: ['Standard Model', 'Predictions'],
    },
    {
        term: 'GW Horizon Comb',
        symbol: 'x_k = ln(k)/(8pi)',
        definition: 'Predicted universal ringdown comb after mass-spin rescaling.',
        category: 'predictions',
        usedIn: ['Predictions'],
    },
    {
        term: 'MOND-Scale Relation',
        symbol: 'a0 ~ c^2 sqrt(Lambda)',
        definition: 'Infrared benchmark scale tied to positive cosmological constant. The paper surface presents suggestive numerics and does not derive a full galaxy-response law.',
        category: 'predictions',
        usedIn: ['Dark Matter', 'Predictions'],
    },
    {
        term: 'No Global Symmetries',
        definition: 'Exact global symmetries are absent in full gauge/gravity patch framework.',
        category: 'predictions',
        usedIn: ['Gauge Symmetry', 'Synthesis'],
    },
    {
        term: 'String Bridge',
        symbol: '2D YM heat kernels',
        definition: 'Edge-sector heat-kernel ensemble equals 2D Yang-Mills partition structure with large-N worldsheet expansion.',
        category: 'predictions',
        usedIn: ['Unification', 'Synthesis'],
    },
    {
        term: 'Strange-Loop Closure',
        symbol: 'Phi(x*) = x*',
        definition: 'Fixed-point explanatory closure connecting observer-compatible physics and observer emergence/reconstruction.',
        category: 'meta',
        usedIn: ['Synthesis'],
    },
    {
        term: 'Intersubjective Reality',
        definition: 'Reality is the overlap-consistent content of patch descriptions, without an external observer-independent state description.',
        category: 'meta',
        usedIn: ['No Objective Reality', 'Synthesis'],
    },
    {
        term: 'Records',
        symbol: 'R',
        definition: 'Stable, shareable patch-internal correlations defining effective measurement outcomes.',
        category: 'methods',
        usedIn: ['Quantum Mechanics', 'Error Correction'],
    },
    {
        term: 'Recovery Map',
        symbol: 'R_{B->BC}',
        definition: 'CPTP map reconstructing missing subsystem information from overlap mediator region when CMI is small.',
        category: 'methods',
        usedIn: ['Error Correction', 'Gravity'],
    },
    {
        term: 'Inconsistency Potential',
        symbol: 'Phi',
        definition: 'Total mismatch functional over overlaps on the finite patch net. Accepted repairs must lower the touched-overlap contribution on the declared branch.',
        category: 'methods',
        usedIn: ['Consensus Protocol'],
    },
    {
        term: 'Lyapunov Functional',
        definition: 'Quantity that decreases along the accepted repair dynamics, ensuring termination on the finite patch net when the local-fit contract is enforced.',
        category: 'methods',
        usedIn: ['Consensus Protocol'],
    },
    {
        term: 'Normal Form',
        definition: 'Repair-fixed patch-net state reached after all accepted local reconciliations are exhausted. Under the stated completeness and gluing assumptions it is schedule-independent.',
        category: 'methods',
        usedIn: ['Consensus Protocol'],
    },
    {
        term: 'Holonomy Obstruction',
        definition: 'Global cycle defect showing that pairwise-compatible overlap data can fail to extend to a single globally consistent configuration.',
        category: 'methods',
        usedIn: ['Consensus Protocol'],
    },
    {
        term: 'Record Algebra',
        definition: 'Observer-accessible algebra generated by exact central record projectors or quantitatively stable approximately commuting surrogates on the fixed-cutoff branch.',
        category: 'methods',
        usedIn: ['Consensus Protocol', 'Screen Microphysics'],
    },
    {
        term: 'Checkpoint / Restoration',
        definition: 'Microphysical backup-and-recovery package used to stabilize records and observer-level state across local repair and synchronization events.',
        category: 'methods',
        usedIn: ['Screen Microphysics'],
    },
    {
        term: 'Finite Screen Reference Architecture',
        definition: 'Chosen finite gauge-register screen model with local links, record registers, overlap observables, and repair dynamics used as the simulator-facing OPH architecture.',
        category: 'methods',
        usedIn: ['Screen Microphysics'],
    },
    {
        term: 'Conditional Mutual Information',
        symbol: 'I(A:D|B)',
        definition: 'Information-theoretic separator measure controlling recoverability and Markov quality.',
        category: 'methods',
        usedIn: ['Entropy', 'Error Correction'],
    },
    {
        term: 'KMS Condition',
        symbol: 'omega(A alpha_t(B)) = omega(alpha_{t+i beta}(B)A)',
        definition: 'Thermal equilibrium characterization with respect to modular flow.',
        category: 'methods',
        usedIn: ['Modular Flow'],
        links: [{ label: 'KMS state (Wikipedia)', url: 'https://en.wikipedia.org/wiki/KMS_state' }],
    },
    {
        term: 'Peter-Weyl Decomposition',
        symbol: 'L^2(G)=sum_R V_R tensor V_R*',
        definition: 'Group harmonic analysis decomposition underlying edge-mode multiplicity and beta-shift effects.',
        category: 'methods',
        usedIn: ['Unification', 'Standard Model'],
        links: [{ label: 'Peter-Weyl theorem', url: 'https://en.wikipedia.org/wiki/Peter%E2%80%93Weyl_theorem' }],
    },
    {
        term: 'Edge Beta Shift',
        symbol: 'Delta b',
        definition: 'Difference between edge-corrected and SM one-loop beta coefficients, used to model OPH edge-sector vacuum-polarization effects.',
        category: 'gauge',
        usedIn: ['Unification', 'Matter Continuations'],
    },
    {
        term: 'One-Loop Running Law',
        symbol: 'alpha_i^-1(mu)=alpha_U^-1+(b_i/2pi)ln(M_U/mu)',
        definition: 'Leading renormalization-group relation used to evolve gauge couplings from unification scale to lower energies.',
        category: 'methods',
        usedIn: ['Unification', 'Matter Continuations'],
    },
    {
        term: 'Threshold Corrections',
        symbol: 'Delta_th',
        definition: 'Finite matching contributions at mass thresholds or scheme changes that perturb pure one-loop running predictions.',
        category: 'methods',
        usedIn: ['Unification', 'Matter Continuations', 'Synthesis'],
        links: [{ label: 'Renormalization group matching', url: 'https://en.wikipedia.org/wiki/Renormalization_group' }],
    },
    {
        term: 'No-Cheat Audit',
        symbol: 'Input contract',
        definition: 'Methodological check that the prediction pipeline depends only on declared inputs (pixel constant and screen capacity) plus derived structures.',
        category: 'meta',
        usedIn: ['Matter Continuations', 'Synthesis'],
    },
];
